import {useEffect, useState} from 'react'
import {Alert, Button, Card, Drawer, Form, Input, message, Modal, Popconfirm, Select, Space, Table, Tag} from 'antd'
import {CheckCircleOutlined, CloudSyncOutlined, DeleteOutlined, DownloadOutlined, EditOutlined, FileAddOutlined, ReloadOutlined, SaveOutlined, UploadOutlined} from '@ant-design/icons'
import {api} from './api'
import {rememberCaseDetailTarget} from './caseDetailNavigation'
import {rememberContractDetailTarget} from './contractDetailNavigation'
import {rememberCustomerDetailTarget} from './customerDetailNavigation'
import {rememberInvestigationDetailTarget} from './investigationDetailNavigation'
type Template={id:number;name:string;category:string;is_active:boolean}
type RecordOption={id:number;serial_no:string;title:string;module:string}
type Job={id:number;job_no:string;template_id:number;template_name:string;record_id:number|null;record_no:string;record_title:string;title:string;instruction:string;content:string;status:string;content_version:number;confirmed_by:string;confirmed_at:string|null;error:string;creator:string;created_at:string;updated_at:string}
const colors:Record<string,string>={已生成:'green',已编辑:'blue',已人工确认:'cyan',生成中:'orange',待配置:'default',生成失败:'red'}
export default function AgentDocumentPage({onNavigate}:{onNavigate?:(route:string)=>void}){
 const [jobs,setJobs]=useState<Job[]>([]),[templates,setTemplates]=useState<Template[]>([]),[records,setRecords]=useState<RecordOption[]>([]),[configured,setConfigured]=useState(false),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[editing,setEditing]=useState<Job|null>(null),[content,setContent]=useState('')
 const [form]=Form.useForm()
 const load=async()=>{setLoading(true);try{const [j,t,...groups]=await Promise.all([api.get('/agent/documents'),api.get('/templates'),...['case','contract','customer','clue','notary','evidence'].map(module=>api.get('/records',{params:{module,page_size:100}}))]);setJobs(j.data.items);setConfigured(j.data.dify_configured);setTemplates(t.data.items.filter((x:Template)=>x.is_active));setRecords(groups.flatMap(r=>r.data.items))}catch{message.error('智能文档数据加载失败')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const create=async()=>{const v=await form.validateFields();try{const {data}=await api.post('/agent/documents',v);message.success(data.status==='待配置'?'任务已创建；配置 Dify 后可重试，当前可先编辑提纲':'智能文档已生成');setOpen(false);load()}catch(error:any){message.error(error?.response?.data?.detail||'创建失败')}}
 const retry=async(row:Job)=>{try{const {data}=await api.post(`/agent/documents/${row.id}/retry`);message.success(data.status==='已生成'?'重新生成成功':data.error||'已提交重试');load()}catch(error:any){message.error(error?.response?.data?.detail||'重试失败')}}
 const save=async()=>{if(!editing)return;try{await api.patch(`/agent/documents/${editing.id}`,{title:editing.title,content});message.success('文档内容已保存');setEditing(null);load()}catch{message.error('保存失败')}}
 const download=async(row:Job)=>{try{const res=await api.get(`/agent/documents/${row.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(res.data),a=document.createElement('a');a.href=url;a.download=`${row.title}.docx`;a.click();URL.revokeObjectURL(url)}catch{message.error('下载失败')}}
 const confirm=async(row:Job)=>{try{await api.post(`/agent/documents/${row.id}/confirm`,{comment:'已人工核对文档内容'});message.success('文档已人工确认，可以回写业务附件');load()}catch(error:any){message.error(error?.response?.data?.detail||'人工确认失败')}}
 const writeback=async(row:Job)=>{try{const {data}=await api.post(`/agent/documents/${row.id}/writeback`);message.success(`已回写为业务附件：${data.filename}`)}catch(error:any){message.error(error?.response?.data?.detail||'回写失败')}}
 const remove=async(row:Job)=>{try{await api.delete(`/agent/documents/${row.id}`);message.success('智能文档任务已删除');if(editing?.id===row.id)setEditing(null);load()}catch(error:any){message.error(error?.response?.data?.detail||'删除失败')}}
 const openRecord=async(row:Job)=>{
  let record=records.find(item=>item.id===row.record_id||item.serial_no===row.record_no)
  if(!record&&row.record_id){try{const {data}=await api.get(`/records/${row.record_id}`);record=data}catch{message.warning('未找到关联业务详情或当前账号无权查看');return}}
  const module=record?.module
  if(module==='case'){rememberCaseDetailTarget({id:record?.id,serial_no:row.record_no});onNavigate?.('case-company');return}
  if(module==='contract'){rememberContractDetailTarget({id:record?.id,serial_no:row.record_no});onNavigate?.('contract-my');return}
  if(module==='customer'){rememberCustomerDetailTarget({id:record?.id,serial_no:row.record_no,title:row.record_title});onNavigate?.('customer-management');return}
  if(module&&['clue','notary','evidence'].includes(module)){rememberInvestigationDetailTarget({id:record?.id,serial_no:row.record_no,module});onNavigate?.(module);return}
  message.warning('未找到关联业务详情或当前账号无权查看')
 }
const columns=[{title:'任务编号',dataIndex:'job_no',width:190},{title:'文档标题',dataIndex:'title',width:240},{title:'模板',dataIndex:'template_name',width:150},{title:'关联业务',key:'record',width:220,render:(_:unknown,r:Job)=>r.record_no?<Button type="link" onClick={()=>void openRecord(r)}>{`${r.record_no}｜${r.record_title}`}</Button>:'未关联'},{title:'状态',dataIndex:'status',width:110,render:(v:string)=><Tag color={colors[v]}>{v}</Tag>},{title:'确认人',dataIndex:'confirmed_by',width:90,render:(v:string)=>v||'—'},{title:'创建人',dataIndex:'creator',width:90},{title:'创建时间',dataIndex:'created_at',width:165,render:(v:string)=>new Date(v).toLocaleString('zh-CN')},{title:'操作',key:'action',width:480,render:(_:unknown,r:Job)=><Space><Button type="link" icon={<EditOutlined/>} onClick={()=>{setEditing(r);setContent(r.content)}}>编辑</Button><Button type="link" icon={<DownloadOutlined/>} onClick={()=>download(r)}>DOCX</Button>{['待配置','生成失败','已生成','已编辑','已人工确认'].includes(r.status)&&<Button type="link" icon={<CloudSyncOutlined/>} onClick={()=>retry(r)}>重新生成</Button>}{['已生成','已编辑'].includes(r.status)&&<Popconfirm title="请确认已逐项人工核对内容；确认后才能回写。" onConfirm={()=>confirm(r)}><Button type="link" icon={<CheckCircleOutlined/>}>人工确认</Button></Popconfirm>}{r.record_id&&<Button type="link" icon={<UploadOutlined/>} disabled={r.status!=='已人工确认'} onClick={()=>writeback(r)}>回写</Button>}<Popconfirm title="确认删除这个智能文档任务？" onConfirm={()=>remove(r)}><Button danger type="link" icon={<DeleteOutlined/>}>删除</Button></Popconfirm></Space>}]
 return <><Alert style={{marginBottom:15}} type={configured?'success':'warning'} showIcon title={configured?'Dify 已配置，可调用智能体生成正式文书':'Dify 尚未配置'} description={configured?'生成时会把模板字段和关联业务数据作为结构化上下文发送给 Dify。':'系统仍会创建可编辑字段提纲；在后端环境变量配置 DIFY_BASE_URL 和 DIFY_API_KEY 后可直接重试。'}/><Card className="panel" title="智能文档中心" extra={<Space><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<FileAddOutlined/>} onClick={()=>{form.resetFields();setOpen(true)}}>生成文档</Button></Space>}><Table rowKey="id" size="small" loading={loading} columns={columns} dataSource={jobs} scroll={{x:1500}} pagination={false}/></Card><Modal open={open} title="创建智能文档任务" okText="开始生成" cancelText="取消" onOk={create} onCancel={()=>setOpen(false)}><Form form={form} layout="vertical"><Form.Item label="文档标题" name="title" rules={[{required:true}]}><Input placeholder="例如：光明乳业案件民事起诉状"/></Form.Item><Form.Item label="文书模板" name="template_id" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={templates.map(x=>({value:x.id,label:`${x.category}｜${x.name}`}))}/></Form.Item><Form.Item label="关联业务" name="record_id"><Select allowClear showSearch optionFilterProp="label" options={records.map(x=>({value:x.id,label:`${x.serial_no}｜${x.title}`}))}/></Form.Item><Form.Item label="补充生成要求" name="instruction"><Input.TextArea rows={4} placeholder="例如：重点论述商标侵权事实，未知金额保留待补充标记"/></Form.Item></Form></Modal><Drawer size={760} open={Boolean(editing)} title="审核与编辑文档" onClose={()=>setEditing(null)} extra={<Button type="primary" icon={<SaveOutlined/>} onClick={save}>保存修改</Button>}>{editing&&<><Input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} style={{marginBottom:12}}/><Input.TextArea value={content} onChange={e=>setContent(e.target.value)} autoSize={{minRows:22}}/><Alert style={{marginTop:12}} type="info" showIcon title="人工审核后再回写或下载；系统不会自动替代律师最终审查。"/></>}</Drawer></>
}
