export const CONTRACT_ATTACHMENT_ACCEPT: string;
export const CONTRACT_ATTACHMENT_MAX_BYTES: number;
export const CONTRACT_ATTACHMENT_LOCKED_STATUSES: readonly string[];
export const CONTRACT_DRAFT_EDITABLE_STATUSES: readonly string[];
export const CONTRACT_LIST_PAGE_SIZES: readonly number[];
export const CONTRACT_QUERY_FIELDS: readonly string[];
export function contractMenuEntries(): Array<{ key: string; label: string; scope: string; legacyPath: string }>;
export function contractListViewConfig(view: string): { scope: string; defaultPageSize: number; statuses: string[]; queryFields: readonly string[] };
export function normalizeContractQuery(values?: Record<string, unknown>): Record<string, unknown>;
export function normalizeContractActionResponse(response: unknown, fallback: string): { ok: boolean; message: string };
export function normalizeContractAttachment(item: unknown): { id: number; original_name: string; uploader: string; created_at: string };
export function normalizeContractApprovalHistory<T extends Record<string, unknown>>(rows: T[]): Array<{ id: number; approver: string; acted_at: string; status: string; comment: string }>;
export function buildContractListRequestParams(view: string, pagination: { current: number; pageSize: number }, query?: Record<string, unknown>): Record<string, unknown>;
export function canAccessContractView(view: string, profile?: { role?: string }): boolean;
export function validateContractApprovalSubmission(status: string, approvers: string, attachmentCount: number): string[];
export function contractAttachmentActionPolicy(status: string): { canUpload: boolean; canDelete: boolean; canDownload: boolean; canPreview: boolean };
export function extractContractErrorMessage(error: unknown, fallback: string): string;
export function contractAuditActionPolicy(view: string): { canReview: boolean; canReviewChange: boolean; canExport: boolean };
export function contractListActionPolicy(status: string | null | undefined): { canPayment: boolean; canInvoice: boolean; canCreateCase: boolean };
export function contractSecondaryActionPolicy(status: string | null | undefined): { canEdit: boolean; canInvestigation: boolean; canArchive: boolean };
export function contractAuditViewConfig(view: string): { statuses: string[] };
export function normalizeContractDetailReturnView(view: string): string;
export function buildContractDraftDefaults(input: {
  serialNo: string;
  profile: { username?: string; department?: string };
  customer?: { id: number; title?: string } | null;
}): {
  serial_no: string;
  status: string;
  owner: string;
  department: string;
  type: string;
  contract_body: string;
  fee_type: string;
  amount: number;
  signed_at: Date;
  customer_id: number | undefined;
  title: string | undefined;
};
export function validateContractDraftValues(values: Record<string, unknown>): string[];
export function resolveContractCustomerSelection<T extends { id: number }>(customerId: number | undefined, customers: T[], linkedCustomer: { id: number; name: string; serial_no?: string } | null, profile: { username?: string }): T | { id: number; serial_no: string; title: string; owner: string; data: { customer_managers: string[] } } | null;
export function filterContractCaseOptions<T extends { customer?: string }>(cases: T[], customer: string): T[];
export function filterContractLinkedRows<T extends { id?: number; contract_record_id?: number; contract_no?: string; data?: { contract_record_id?: number; contract_id?: number; contract_no?: string } }>(rows: T[], contract: { id?: number; serial_no?: string }): T[];
export function canActOnContractApproval(status: string, approver: string, username: string, role: string): boolean;
export function buildContractApprovalPayload(approved: boolean, comment: unknown): { approved: boolean; comment: string };
export function canMutateContractAttachments(status: string): boolean;
export function validateContractAttachment(file: { size?: number } | null | undefined): string | null;
