import {useEffect, useMemo, useState} from 'react'
import {Button, Card, DatePicker, Descriptions, Empty, Form, Input, InputNumber, message, Modal, Popconfirm, Radio, Select, Space, Switch, Table, Tabs, Upload} from 'antd'
import type {TableColumnsType} from 'antd'
import type {ReactNode} from 'react'
import dayjs from 'dayjs'
import {DownloadOutlined, EditOutlined, PlusOutlined, UploadOutlined} from '@ant-design/icons'
import {api} from './api'
import {formatRequiredDate} from './formSafety'
import './hr-center.css'

type Employee={id:number;serial_no:string;title:string;customer:string;status:string;owner:string;department:string;description:string;data:Record<string,any>;created_at:string}
type OrganizationOption={name:string;code?:string;is_active:boolean}
const companyName='上海申浩律师事务所'
const roleOptions=[{value:'admin',label:'系统管理员'},{value:'manager',label:'部门负责人'},{value:'auditor',label:'审批人员'},{value:'user',label:'普通用户'}]
const staffRoleOptions=['合作律师','系统管理员','业务代表','行政流程','财务','授薪律师','财务审核管理','档案审核管理','合伙人律师','专利代理人','商标代理人','前台','实习律师','调查取证员','律师助理','律所财务','知产中心负责人','诉讼部部长','调查部部长','外部合作调查取证员','离职过渡','实习助理','案件审核管理','客户联系人','外部合作调查员','律师+客户审核','实习生-调查部','测试','案例编辑人员','外部案源人'].map(value=>({value,label:value}))
const systemRoleOf=(staffRole:string)=>staffRole==='系统管理员'?'admin':/审核|负责人|部长|合伙人/.test(staffRole)?'manager':/财务/.test(staffRole)?'auditor':'user'
const employeeDateFields=['graduation_date','agent_qualification_date','agent_practice_date','lawyer_license_date','training_date','agent_intern_start','agent_intern_end','partner_start','partner_end','joined_at','left_at','contract_end']
const accountTypes=['员工账号','客户账号','外部合作账号'].map(value=>({value,label:value}))
const dataLevels=['公司','部门','本人'].map(value=>({value,label:value}))
const employeeNo=()=>`RS${dayjs().format('YYYYMMDDHHmmss')}`

type SubrecordKind='leave'|'matter'|'commission'
type Subrecord={id:number;employee_id:number;kind:SubrecordKind;data:Record<string,any>;created_by:string;created_at:string}
type Attachment={id:number;original_name:string;uploader:string;created_at:string;size:number}

function EmployeeSubrecords({employeeId,kind}:{employeeId?:number;kind:SubrecordKind|'archive'}){
  const [rows,setRows]=useState<(Subrecord|Attachment)[]>([]),[loading,setLoading]=useState(false),[editing,setEditing]=useState<Subrecord|null>(null),[open,setOpen]=useState(false),[form]=Form.useForm()
  const load=async()=>{if(!employeeId){setRows([]);return}setLoading(true);try{const {data}=kind==='archive'?await api.get('/attachments',{params:{record_id:employeeId,category:'员工档案'}}):await api.get(`/hr/${employeeId}/subrecords`,{params:{kind}});setRows(data.items)}catch{message.error('员工附属记录加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[employeeId,kind])
  if(!employeeId)return <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="请先保存员工基本信息，再维护此页记录"/>
  const remove=async(id:number)=>{try{await api.delete(kind==='archive'?`/attachments/${id}`:`/hr/${employeeId}/subrecords/${id}`);message.success('删除成功');void load()}catch(error:any){message.error(error?.response?.data?.detail||'删除失败')}}
  const download=async(item:Attachment)=>{try{const response=await api.get(`/attachments/${item.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=url;anchor.download=item.original_name;anchor.click();URL.revokeObjectURL(url)}catch{message.error('文件下载失败')}}
  const showEditor=(item?:Subrecord)=>{setEditing(item||null);const values={...(item?.data||{})};['start_date','end_date','operation_date'].forEach(key=>{if(values[key])values[key]=dayjs(values[key])});form.setFieldsValue(values);setOpen(true)}
  const save=async()=>{try{const values=await form.validateFields();['start_date','end_date','operation_date'].forEach(key=>{if(dayjs.isDayjs(values[key]))values[key]=values[key].format('YYYY-MM-DD')});if(editing)await api.patch(`/hr/${employeeId}/subrecords/${editing.id}`,{data:values});else await api.post(`/hr/${employeeId}/subrecords`,{kind,data:values});message.success(editing?'修改成功':'新增成功');setOpen(false);form.resetFields();void load()}catch(error:any){if(error?.errorFields)return;message.error(error?.response?.data?.detail||'保存失败')}}
  if(kind==='archive'){
    const columns:TableColumnsType<any>=[{title:'序号',width:65,render:(_v,_r,i)=>i+1},{title:'上传人',dataIndex:'uploader',width:120},{title:'文件名称',dataIndex:'original_name'},{title:'文档日期',dataIndex:'created_at',width:180,render:v=>dayjs(v).format('YYYY-MM-DD HH:mm')},{title:'查看',width:75,render:(_v,r)=><Button type="link" icon={<DownloadOutlined/>} onClick={()=>void download(r)}>下载</Button>},{title:'操作',width:75,render:(_v,r)=><Popconfirm title="确认删除该员工文档？" onConfirm={()=>void remove(r.id)}><Button type="link" danger>删除</Button></Popconfirm>}]
    return <div className="employee-subrecord"><div className="subrecord-toolbar"><Upload showUploadList={false} customRequest={async options=>{const data=new FormData();data.append('file',options.file as Blob);data.append('record_id',String(employeeId));data.append('category','员工档案');try{await api.post('/attachments',data,{headers:{'Content-Type':'multipart/form-data'}});options.onSuccess?.({});message.success('员工文档上传成功');void load()}catch(error:any){options.onError?.(error);message.error(error?.response?.data?.detail||'上传失败')}}}><Button type="primary" icon={<UploadOutlined/>}>上传员工文档</Button></Upload></div><Table rowKey="id" size="small" loading={loading} columns={columns} dataSource={rows} pagination={false}/></div>
  }
  const action={title:'操作',width:130,render:(_v:any,r:Subrecord)=><Space size={0}><Button type="link" icon={<EditOutlined/>} onClick={()=>showEditor(r)}>编辑</Button><Popconfirm title="确认删除该记录？" onConfirm={()=>void remove(r.id)}><Button type="link" danger>删除</Button></Popconfirm></Space>}
  const columns:TableColumnsType<any>=kind==='leave'?[{title:'请假开始',dataIndex:['data','start_date']},{title:'请假结束',dataIndex:['data','end_date']},{title:'小时',dataIndex:['data','hours']},{title:'类型',dataIndex:['data','leave_type']},{title:'备注',dataIndex:['data','remark']},action]:kind==='matter'?[{title:'序号',width:65,render:(_v,_r,i)=>i+1},{title:'内容',dataIndex:['data','content']},{title:'操作人',dataIndex:'created_by',width:120},{title:'操作日期',dataIndex:['data','operation_date'],width:120},action]:[{title:'序号',width:65,render:(_v,_r,i)=>i+1},{title:'开始',dataIndex:['data','start_date']},{title:'结束',dataIndex:['data','end_date']},{title:'基本工资',dataIndex:['data','base_salary']},{title:'开庭比例/固定',dataIndex:['data','hearing_rate']},{title:'文书比例/固定',dataIndex:['data','document_rate']},{title:'案源比例/固定',dataIndex:['data','source_rate']},{title:'调查比例/固定',dataIndex:['data','investigation_rate']},{title:'品管比例/固定',dataIndex:['data','quality_rate']},action]
  const title=kind==='leave'?'请假记录':kind==='matter'?'事项记录':'提成设定'
  return <div className="employee-subrecord"><div className="subrecord-toolbar"><Button type="primary" icon={<PlusOutlined/>} onClick={()=>showEditor()}>新建</Button></div><Table rowKey="id" size="small" loading={loading} columns={columns} dataSource={rows} pagination={false}/><Modal open={open} title={`${editing?'编辑':'新建'}${title}`} okText="保存" cancelText="取消" onOk={()=>void save()} onCancel={()=>{setOpen(false);form.resetFields()}} destroyOnHidden><Form form={form} layout="vertical">{kind==='leave'?<><Form.Item name="start_date" label="请假开始" rules={[{required:true}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="end_date" label="请假结束" rules={[{required:true}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="hours" label="小时" rules={[{required:true}]}><InputNumber min={0.5} step={0.5} style={{width:'100%'}}/></Form.Item><Form.Item name="leave_type" label="类型" rules={[{required:true}]}><Select options={['事假','病假','年假','婚假','产假','调休','其他'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="remark" label="备注"><Input.TextArea/></Form.Item></>:kind==='matter'?<><Form.Item name="content" label="内容" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item><Form.Item name="operation_date" label="操作日期" initialValue={dayjs()} rules={[{required:true}]}><DatePicker style={{width:'100%'}}/></Form.Item></>:<><div className="commission-form-grid"><Form.Item name="start_date" label="开始" rules={[{required:true}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="end_date" label="结束"><DatePicker style={{width:'100%'}}/></Form.Item>{[['base_salary','基本工资'],['hearing_rate','开庭比例/固定'],['document_rate','文书比例/固定'],['source_rate','案源比例/固定'],['investigation_rate','调查比例/固定'],['quality_rate','品管比例/固定']].map(([key,label])=><Form.Item key={key} name={key} label={label} initialValue={0}><InputNumber min={0} precision={2} style={{width:'100%'}}/></Form.Item>)}</div></>}</Form></Modal></div>
}

export default function HrCenterPage({initialView='hr-all'}:{initialView?:string}){
  const isNew=initialView==='hr-new'
  const [rows,setRows]=useState<Employee[]>([]),[loading,setLoading]=useState(false)
  const [company,setCompany]=useState(companyName),[department,setDepartment]=useState(''),[username,setUsername]=useState(''),[name,setName]=useState(''),[mobile,setMobile]=useState(''),[enabled,setEnabled]=useState('')
  const [departments,setDepartments]=useState<{value:string;label:string}[]>([]),[positions,setPositions]=useState<{value:string;label:string}[]>([])
  const [topTab,setTopTab]=useState(isNew?'new':'list'),[form]=Form.useForm()
  const accountType=Form.useWatch('account_type',form)||'员工账号'
  const [viewing,setViewing]=useState<Employee|null>(null),[currentEmployeeId,setCurrentEmployeeId]=useState<number|undefined>()
  const [editingEmployee,setEditingEmployee]=useState<Employee|null>(null),[employeeEditForm]=Form.useForm(),[savingEmployee,setSavingEmployee]=useState(false)
  const [transitioningEmployee,setTransitioningEmployee]=useState<Employee|null>(null),[transitionForm]=Form.useForm(),[transitionSaving,setTransitionSaving]=useState(false)
  const load=async()=>{setLoading(true);try{
    const [employeeResult,userResult]=await Promise.all([api.get('/records',{params:{module:'hr',page_size:100}}),api.get('/system/users')])
    const employees:Employee[]=employeeResult.data.items||[]
    const existing=new Set(employees.map(row=>String(row.data?.username||row.owner).toLowerCase()))
    const accountOnly:Employee[]=(userResult.data.items||[]).filter((user:any)=>!existing.has(String(user.username).toLowerCase())).map((user:any)=>({
      id:-Number(user.id),serial_no:user.profile?.employee_no||`SYS-${String(user.id).padStart(4,'0')}`,title:user.display_name||user.username,
      customer:user.profile?.company||companyName,status:user.is_active?'在职':'停用',owner:user.username,department:user.department||'',description:'系统账号（尚未建立独立人事档案）',created_at:user.created_at,
      data:{...(user.profile||{}),username:user.username,role:user.role,is_active:user.is_active,system_user_id:user.id,position:user.profile?.position||'系统管理员'},
    }))
    setRows([...employees,...accountOnly])
  }catch{message.error('员工数据加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load();Promise.all([api.get('/hr/departments',{params:{active_only:true}}),api.get('/hr/job-roles',{params:{active_only:true}})]).then(([ds,rs])=>{setDepartments(ds.data.items.map((item:OrganizationOption)=>({value:item.name,label:item.name})));setPositions(rs.data.items.map((item:OrganizationOption)=>({value:item.name,label:item.name})))}).catch(()=>message.error('部门与职务加载失败'))},[])
  useEffect(()=>{setTopTab(isNew?'new':'list')},[isNew])
  const resetNewEmployee=()=>{setCurrentEmployeeId(undefined);form.resetFields();form.setFieldsValue({serial_no:employeeNo(),company:companyName,data_level:'公司',is_active:true,account_type:'员工账号',role:undefined,joined_at:dayjs()})}
  useEffect(()=>{if(isNew)resetNewEmployee()},[isNew])

  const filtered=useMemo(()=>rows.filter(row=>{const d=row.data||{};return (!company||row.customer===company)&&(!department||row.department===department)&&(!username||String(d.username||row.owner).includes(username))&&(!name||row.title.includes(name))&&(!mobile||String(d.mobile||d.phone||'').includes(mobile))&&(!enabled||(d.is_active!==false?'是':'否')===enabled)}),[rows,company,department,username,name,mobile,enabled])
  const saveEmployee=async()=>{if(currentEmployeeId){message.info('员工基本信息已保存，请通过员工列表的“修改”维护资料');return}const value=await form.validateFields();const data={...value,staff_role:value.role};delete data.password;delete data.title;delete data.serial_no;delete data.company;delete data.department;delete data.role;delete data.username;for(const key of Object.keys(data)){if(dayjs.isDayjs(data[key]))data[key]=data[key].format('YYYY-MM-DD')}try{const {data:result}=await api.post('/hr/employees',{username:value.username||'',display_name:value.title,employee_no:value.serial_no,company:value.company,department:value.department,password:value.password||'',role:systemRoleOf(value.role),position:value.position,is_active:value.is_active,account_type:value.account_type,data});setCurrentEmployeeId(result.employee.id);message.success(value.account_type==='员工账号'?'员工档案与低权限登录账号已同步保存':'员工档案保存成功（未创建系统登录账号）');void load()}catch(error:any){message.error(error?.response?.data?.detail||'员工保存失败')}}
  const openEmployeeEdit=async(row:Employee)=>{try{const {data}=await api.get('/system/users',{params:{keyword:row.data.username||row.owner}});const account=data.items.find((item:any)=>item.username===(row.data.username||row.owner));const profileData={...(account?.profile||{}),...(row.data||{})};const dateValues=Object.fromEntries(employeeDateFields.map(key=>[key,profileData[key]?dayjs(profileData[key]):key==='joined_at'?dayjs():undefined]));employeeEditForm.resetFields();employeeEditForm.setFieldsValue({...profileData,...dateValues,display_name:row.title,department:row.department,system_role:account?.role||row.data.role||'user',staff_role:profileData.staff_role||profileData.position||'普通用户',position:profileData.position||'',email:profileData.email||account?.email||'',mobile:profileData.mobile||account?.mobile||'',extension:profileData.extension||profileData.office_phone||account?.office_phone||'',is_active:row.data.is_active!==false});setEditingEmployee(row)}catch(error:any){message.error(error?.response?.data?.detail||'员工账号资料加载失败')}}
  const saveEmployeeEdit=async()=>{if(!editingEmployee)return;const value=await employeeEditForm.validateFields();const editableData:Record<string,any>={...editingEmployee.data,username:value.username};for(const [key] of basicFields){if(['serial_no','username','password','company','title'].includes(key))continue;const formKey=key==='role'?'staff_role':key;const fieldValue=value[formKey];editableData[key]=dayjs.isDayjs(fieldValue)?fieldValue.format('YYYY-MM-DD'):fieldValue??''}editableData.staff_role=value.staff_role;setSavingEmployee(true);try{
    if(editingEmployee.id<0){
      await api.patch(`/system/users/${editingEmployee.data.system_user_id||-editingEmployee.id}`,{username:value.username,display_name:value.display_name,department:value.department,role:value.system_role,is_active:value.is_active,profile:{...editableData,position:value.position,email:value.email||'',mobile:value.mobile||'',office_phone:value.extension||'',joined_at:formatRequiredDate(value.joined_at,'加入日期'),left_at:value.left_at?.format('YYYY-MM-DD')||''}})
      message.success('系统账号资料已更新')
    }else{
      await api.patch(`/hr/employees/${editingEmployee.id}`,{username:value.username,display_name:value.display_name,department:value.department,role:value.system_role,position:value.position,is_active:editingEmployee.status!=='离职'&&editingEmployee.status!=='停用',email:value.email||'',mobile:value.mobile||'',office_phone:value.extension||'',joined_at:formatRequiredDate(value.joined_at,'加入日期'),left_at:value.left_at?.format('YYYY-MM-DD')||null,data:editableData})
      message.success('员工档案与登录账号已同步修改')
    }
    setEditingEmployee(null);await load()
  }catch(error:any){message.error(error?.response?.data?.detail||'员工修改失败')}finally{setSavingEmployee(false)}}
  const transitionOptions=(status:string)=>status==='试用'?['在职','离职']:status==='在职'?['离职','停用']:[]
  const openTransition=(row:Employee)=>{if(row.id<0){message.info('尚未建立人事档案的系统账号，请先补建员工档案后再办理人事状态');return}const options=transitionOptions(row.status);if(!options.length){message.info(`员工当前为“${row.status}”，暂无可办理的人事状态`);return}transitionForm.resetFields();transitionForm.setFieldsValue({to_status:options[0],effective_date:dayjs(),reason:'',handover_to:'',comment:''});setTransitioningEmployee(row)}
  const saveTransition=async()=>{if(!transitioningEmployee)return;const value=await transitionForm.validateFields();setTransitionSaving(true);try{await api.post(`/hr/employees/${transitioningEmployee.id}/transition`,{...value,effective_date:formatRequiredDate(value.effective_date,'办理日期')});message.success('人事状态及关联登录账号已同步更新');setTransitioningEmployee(null);await load()}catch(error:any){message.error(error?.response?.data?.detail||'人事状态办理失败')}finally{setTransitionSaving(false)}}

  const columns:TableColumnsType<Employee>=[
    {title:'序号',key:'no',width:65,render:(_v,_r,i)=>i+1},{title:'员工号',dataIndex:'serial_no',width:150},{title:'用户名',key:'username',width:120,render:(_v,r)=>r.data.username||r.owner},{title:'中文姓名',dataIndex:'title',width:110},{title:'所属部门',dataIndex:'department',width:150},{title:'所属公司',dataIndex:'customer',width:190},{title:'Email',key:'email',width:190,render:(_v,r)=>r.data.email||'—'},{title:'手机号码',key:'mobile',width:135,render:(_v,r)=>r.data.mobile||r.data.phone||'—'},{title:'固定电话',key:'office',width:125,render:(_v,r)=>r.data.office_phone||r.data.extension||'—'},{title:'是否可用',key:'active',width:90,render:(_v,r)=>r.data.is_active===false?'否':'是'},{title:'操作',key:'action',width:190,render:(_v,r)=><Space size={0}><Button type="link" onClick={()=>setViewing(r)}>查看</Button><Button type="link" icon={<EditOutlined/>} onClick={()=>void openEmployeeEdit(r)}>修改</Button><Button type="link" onClick={()=>openTransition(r)}>办理状态</Button></Space>},
  ]
  const listPanel=<><div className="hr-query"><label><span>公司</span><Select value={company} onChange={setCompany} options={[{value:companyName,label:companyName}]}/></label><label><span>部门</span><Select value={department} onChange={setDepartment} allowClear placeholder="请选择" options={departments}/></label><label><span>用户名</span><Input value={username} onChange={e=>setUsername(e.target.value)} allowClear/></label><label><span>中文名</span><Input value={name} onChange={e=>setName(e.target.value)} allowClear/></label><label><span>手机号</span><Input value={mobile} onChange={e=>setMobile(e.target.value)} allowClear/></label><label><span>是否可用</span><Select value={enabled} onChange={setEnabled} options={[{value:'',label:'请选择'},{value:'是',label:'是'},{value:'否',label:'否'}]}/></label><Button type="primary" onClick={()=>void load()}>查询</Button></div><Table rowKey="id" size="small" loading={loading} columns={columns} dataSource={filtered} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无数据"/>}} pagination={{pageSize:20,showTotal:total=>`共 ${total} 条`}} scroll={{x:1450}}/></>

  const basicFields:[string,string,'input'|'select'|'date'|'number',any?][]=[
    ['serial_no','员工号*','input'],['username','用户名*','input'],['title','中文姓名*','input'],['role','角色*','select',staffRoleOptions],['password','密码*','input'],
    ['company','公司*','select',[{value:companyName,label:companyName}]],['department','部门*','select',departments],['position','职务*','select',positions],['data_level','数据级别*','select',dataLevels],
    ['account_type','账号类型','select',accountTypes],['id_no','身份证号','input'],['mobile','手机','input'],['english_level','英语等级','input'],['education','专业学历','input'],['extension','分机','input'],['native_place','籍贯','input'],['foreign_language','外语','input'],['graduation_date','毕业时间','date'],['social_security','社保情况','input'],['school','毕业学校','input'],['address','住址','input'],['id_address','身份证地址','input'],
    ['agent_qualification_no','代理人资格证号','input'],['agent_qualification_date','取得资格证日期','date'],['agent_practice_no','代理人执业证号','input'],['agent_practice_date','取得代理人执业证日期','date'],['professional_title','职称','input'],['social_position','社会职务','input'],['lawyer_license_no','律师执业证号','input'],['lawyer_license_date','取得律师职业证日期','date'],['political_status','政治面貌','input'],['training_date','上岗培训时间','date'],['agent_intern_start','代理人实习开始日期','date'],['agent_intern_end','代理人实习期结束日期','date'],['partner_start','合伙人开始日期','date'],['partner_end','合伙人结束日期','date'],['joined_at','加入日期','date'],['left_at','离职日期','date'],['job_title','职位','input'],['level','级别','input'],['annual_leave','年休剩余日数','number'],['source_rate','案源提成比','number'],['gender','性别','select',['男','女'].map(value=>({value,label:value}))],['marriage','婚姻状况','input'],['childbearing','生育状况','input'],['writing_rate','撰稿提成比','number'],['contract_end','合同到期日','date'],['employment_status','在职情况','input'],['email','Email','input'],['im','IM','input'],
  ]
  const employeeEditFields=basicFields.filter(([key])=>!['serial_no','username','password','company','title'].includes(key))
  const basic=<Form form={form} className="employee-form" labelCol={{flex:'120px'}} labelAlign="right" disabled={Boolean(currentEmployeeId)}> <div className="employee-form-grid">{basicFields.filter(([key])=>accountType==='员工账号'||!['username','password'].includes(key)).map(([key,label,type,options])=><Form.Item key={key} name={key} label={label.replace('*','')} rules={label.includes('*')?[{required:true,message:`请填写${label.replace('*','')}`}]:[]}>{type==='select'?<Select placeholder="请选择" options={options}/>:type==='date'?<DatePicker style={{width:'100%'}}/>:type==='number'?<InputNumber min={0} style={{width:'100%'}}/>:key==='password'?<Input.Password/>:<Input/>}</Form.Item>)}<Form.Item label="是否可用" name="is_active"><Radio.Group><Radio value={true}>是</Radio><Radio value={false}>否</Radio></Radio.Group></Form.Item></div>{accountType==='员工账号'&&<div className="employee-account-tip">员工账号保存时会原子创建或同步一个普通用户登录账号；职务岗位仍独立决定调查等业务权限。</div>}<div className="employee-save"><Space><Button type="primary" disabled={Boolean(currentEmployeeId)} onClick={saveEmployee}>{currentEmployeeId?'基本信息已保存':'保存'}</Button>{currentEmployeeId&&<Button onClick={resetNewEmployee}>继续新建员工</Button>}</Space></div></Form>
  const employeeTabs=(employeeId?:number,basicNode?:ReactNode)=><Tabs items={[...(basicNode?[{key:'basic',label:'基本信息',children:basicNode}]:[]),{key:'leave',label:'请假记录',children:<EmployeeSubrecords employeeId={employeeId} kind="leave"/>},{key:'matter',label:'事项记录',children:<EmployeeSubrecords employeeId={employeeId} kind="matter"/>},{key:'archive',label:'员工档案',children:<EmployeeSubrecords employeeId={employeeId} kind="archive"/>},{key:'commission',label:'提成设定',children:<EmployeeSubrecords employeeId={employeeId} kind="commission"/>}]}/>
  const newPanel=employeeTabs(currentEmployeeId,basic)
  const details=viewing?<Descriptions bordered size="small" column={2} items={[{key:'serial',label:'员工号',children:viewing.serial_no},{key:'username',label:'用户名',children:viewing.data.username||viewing.owner},{key:'name',label:'中文姓名',children:viewing.title},{key:'company',label:'所属公司',children:viewing.customer},{key:'department',label:'所属部门',children:viewing.department},{key:'position',label:'职务',children:viewing.data.position||'—'},{key:'email',label:'Email',children:viewing.data.email||'—'},{key:'mobile',label:'手机号码',children:viewing.data.mobile||viewing.data.phone||'—'},{key:'office',label:'固定电话',children:viewing.data.office_phone||viewing.data.extension||'—'},{key:'joined',label:'加入日期',children:viewing.data.joined_at||'—'},{key:'status',label:'在职情况',children:viewing.status},{key:'active',label:'是否可用',children:viewing.data.is_active===false?'否':'是'}]}/>:null
  const detail=<Modal open={Boolean(viewing)} title={`员工查看：${viewing?.title||''}`} footer={null} width={1100} onCancel={()=>setViewing(null)} destroyOnHidden>{viewing&&(viewing.id<0?<><Descriptions bordered size="small" column={2} items={[{key:'serial',label:'员工号',children:viewing.serial_no},{key:'username',label:'用户名',children:viewing.data.username||viewing.owner},{key:'name',label:'中文姓名',children:viewing.title},{key:'company',label:'所属公司',children:viewing.customer},{key:'department',label:'所属部门',children:viewing.department},{key:'position',label:'职务',children:viewing.data.position||'—'},{key:'status',label:'账号状态',children:viewing.status},{key:'note',label:'说明',children:'该账号已纳入员工列表；补充完整人事资料后可维护请假、档案和提成记录。',span:2}]}/></>:employeeTabs(viewing.id,details))}</Modal>
  const editModal=<Modal open={Boolean(editingEmployee)} title={`员工完整资料修改：${editingEmployee?.serial_no||''}`} width={1120} styles={{body:{maxHeight:'70vh',overflowY:'auto'}}} okText="保存全部修改" cancelText="取消" confirmLoading={savingEmployee} onOk={()=>void saveEmployeeEdit()} onCancel={()=>setEditingEmployee(null)} destroyOnHidden><Form form={employeeEditForm} layout="vertical"><div className="employee-form-grid"><Form.Item name="username" label="用户名" rules={[{required:true,message:'请输入用户名'},{min:3,message:'用户名至少 3 位'},{pattern:/^[A-Za-z0-9._-]+$/,message:'只能包含字母、数字、点、下划线或短横线'}]}><Input autoComplete="off"/></Form.Item><Form.Item name="display_name" label="中文姓名" rules={[{required:true,message:'请输入中文姓名'}]}><Input/></Form.Item>{employeeEditFields.map(([key,label,type,options])=>{const name=key==='role'?'staff_role':key;const shownLabel=key==='role'?'人员角色':label.replace('*','');const rules:any[]=[];if(label.includes('*')||key==='joined_at')rules.push({required:true,message:`请填写${shownLabel}`});if(key==='email')rules.push({type:'email',message:'Email格式不正确'});return <Form.Item key={key} name={name} label={shownLabel} rules={rules}>{type==='select'?<Select placeholder="请选择" options={options}/>:type==='date'?<DatePicker style={{width:'100%'}}/>:type==='number'?<InputNumber min={0} style={{width:'100%'}}/>:<Input/>}</Form.Item>})}<Form.Item name="system_role" label="系统权限角色" rules={[{required:true,message:'请选择系统权限角色'}]}><Select options={roleOptions}/></Form.Item><Form.Item label="账号状态"><Switch checked={editingEmployee?.status!=='离职'&&editingEmployee?.status!=='停用'} disabled checkedChildren="是" unCheckedChildren="否"/><div className="employee-account-tip">账号启停请使用列表中的“办理状态”，系统会同步人事状态、原因和生效日期。</div></Form.Item></div></Form></Modal>
  const transitionModal=<Modal open={Boolean(transitioningEmployee)} title={`办理人事状态：${transitioningEmployee?.serial_no||''}`} okText="确认办理" cancelText="取消" confirmLoading={transitionSaving} onOk={()=>void saveTransition()} onCancel={()=>setTransitioningEmployee(null)} destroyOnHidden><Form form={transitionForm} layout="vertical"><Form.Item label="目标状态" name="to_status" rules={[{required:true,message:'请选择目标状态'}]}><Select options={transitionOptions(transitioningEmployee?.status||'').map(value=>({value,label:value}))}/></Form.Item><Form.Item label="生效日期" name="effective_date" rules={[{required:true,message:'请选择生效日期'}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item label="办理原因" name="reason" rules={[{required:true,min:2,message:'请填写至少两个字符的办理原因'}]}><Input.TextArea rows={3}/></Form.Item><Form.Item label="交接给" name="handover_to"><Input placeholder="离职交接时填写接收账号或姓名"/></Form.Item><Form.Item label="办理说明" name="comment"><Input.TextArea rows={2}/></Form.Item></Form></Modal>
  if(!isNew)return <><Card className="panel hr-panel" title="员工列表">{listPanel}</Card>{detail}{editModal}{transitionModal}</>
  return <><Card className="panel hr-panel" title="员工信息"><Tabs activeKey={topTab} onChange={setTopTab} items={[{key:'new',label:'员工新建',children:newPanel},{key:'list',label:'员工列表',children:listPanel}]}/></Card>{detail}{editModal}{transitionModal}</>
}
