import {useEffect, useMemo, useState} from 'react'
import {Button, Card, DatePicker, Descriptions, Empty, Form, Input, InputNumber, message, Modal, Popconfirm, Radio, Select, Space, Switch, Table, Tabs, Tooltip, Upload} from 'antd'
import type {TableColumnsType} from 'antd'
import type {ReactNode} from 'react'
import dayjs from 'dayjs'
import {DownloadOutlined, EditOutlined, EyeOutlined, PlusOutlined, UploadOutlined} from '@ant-design/icons'
import {api} from './api'
import {consumeBusinessRecordDetailTarget} from './businessRecordDetailNavigation'
import {formatRequiredDate} from './formSafety'
// @ts-ignore The legacy required-field order is covered by a standalone Node test.
import {firstMissingRequiredEmployeeField} from './employeeBasicParity.mjs'
// @ts-ignore The tiny guard is also exercised by the standalone Node test.
import {employeeSubrecordCreateMessage} from './employeeSubrecordGuard.mjs'
// @ts-ignore Role-gated HR actions are covered by a standalone Node test.
import {hrActionAccess, hrTransitionOptions, hrTransitionReasonMessage} from './hrAccessGuard.mjs'
// @ts-ignore The selected-id contract is covered by a standalone Node test.
import {normalizeEmployeeIds} from './employeeBulkDelete.mjs'
// @ts-ignore Fixed employee options are shared with standalone behavior tests.
import {employeeSelectOptions, legacyEmployeeBasicDefaults} from './employeeBasicSelectOptions.mjs'
import './hr-center.css'

type Employee={id:number;serial_no:string;title:string;customer:string;status:string;owner:string;department:string;description:string;data:Record<string,any>;created_at:string}
type DeletionBlocker={kind:string;count:number;records:string[]}
type DeletionImpact={deletable:boolean;blockers:DeletionBlocker[]}
type OrganizationOption={name:string;code?:string;is_active:boolean}
const companyName='上海申浩律师事务所'
const baseRoleOptions=[{value:'admin',label:'系统管理员'},{value:'manager',label:'部门负责人'},{value:'auditor',label:'审批人员'},{value:'user',label:'普通用户'}]
const businessRoleValue=(role:string)=>`business:${role}`
const selectedBusinessRole=(value:string)=>value?.startsWith('business:')?value.slice('business:'.length):''
const staffRoleOptions=['合作律师','系统管理员','业务代表','行政流程','财务','授薪律师','财务审核管理','档案审核管理','合伙人律师','专利代理人','商标代理人','前台','实习律师','调查取证员','律师助理','律所财务','知产中心负责人','诉讼部部长','调查部部长','外部合作调查取证员','离职过渡','实习助理','案件审核管理','客户联系人','外部合作调查员','律师+客户审核','实习生-调查部','测试','案例编辑人员','外部案源人'].map(value=>({value,label:value}))
const systemRoleOf=(staffRole:string)=>staffRole==='系统管理员'?'admin':/审核|负责人|部长|合伙人/.test(staffRole)?'manager':/财务/.test(staffRole)?'auditor':'user'
const effectiveSystemRoleOf=(systemRole:string)=>{const permissionRole=selectedBusinessRole(systemRole);return permissionRole?systemRoleOf(permissionRole):systemRole}
const canConfigureContractApproval=(systemRole:string,employeeId?:number,accountType='员工账号')=>Boolean(accountType==='员工账号'&&employeeId&&employeeId>0&&effectiveSystemRoleOf(systemRole)!=='admin')
const employeeDateFields=['graduation_date','agent_qualification_date','agent_practice_date','lawyer_license_date','training_date','agent_intern_start','agent_intern_end','partner_start','partner_end','joined_at','left_at','contract_end']
const accountTypes=['员工账号','客户账号','外部合作账号'].map(value=>({value,label:value}))
const dataLevels=['公司','部门','本人'].map(value=>({value,label:value}))

type SubrecordKind='leave'|'matter'|'commission'
type Subrecord={id:number;employee_id:number;kind:SubrecordKind;data:Record<string,any>;created_by:string;created_at:string}
type Attachment={id:number;original_name:string;uploader:string;created_at:string;size:number}
type AttachmentPreview={name:string;kind:'image'|'pdf'|'text'|'docx';url?:string;text?:string}
const commissionDefaults={base_salary:0,hearing_rate:0.10,hearing_fixed:0,document_rate:0.05,document_fixed:0,source_rate:0.05,source_fixed:0,investigation_rate:0.05,investigation_fixed:0,quality_rate:0.02,quality_fixed:0}

function EmployeeSubrecords({employeeId,kind,canManage=true}:{employeeId?:number;kind:SubrecordKind|'archive';canManage?:boolean}){
  const [rows,setRows]=useState<(Subrecord|Attachment)[]>([]),[loading,setLoading]=useState(false),[editing,setEditing]=useState<Subrecord|null>(null),[open,setOpen]=useState(false),[uploadOpen,setUploadOpen]=useState(false),[uploadFile,setUploadFile]=useState<File|null>(null),[performanceCases,setPerformanceCases]=useState<{value:number;label:string}[]>([]),[performanceCaseId,setPerformanceCaseId]=useState<number|undefined>(),[resolvedPerformance,setResolvedPerformance]=useState<any>(null),[performanceLoading,setPerformanceLoading]=useState(false),[leaveQueryDraft,setLeaveQueryDraft]=useState(''),[leaveQuery,setLeaveQuery]=useState(''),[subrecordPage,setSubrecordPage]=useState(1),[form]=Form.useForm()
  const load=async()=>{if(!employeeId){setRows([]);return}setLoading(true);try{const {data}=kind==='archive'?await api.get('/attachments',{params:{record_id:employeeId,category:'员工档案'}}):await api.get(`/hr/${employeeId}/subrecords`,{params:{kind}});setRows(data.items)}catch{message.error('员工附属记录加载失败')}finally{setLoading(false)}}
  useEffect(()=>{setSubrecordPage(1);setLeaveQueryDraft('');setLeaveQuery('');void load()},[employeeId,kind])
  useEffect(()=>{if(kind!=='commission'){setPerformanceCases([]);setPerformanceCaseId(undefined);setResolvedPerformance(null);return}let active=true;void api.get('/records',{params:{module:'case',page_size:100}}).then(({data})=>{if(active)setPerformanceCases((data.items||[]).map((item:any)=>({value:item.id,label:`${item.serial_no}｜${item.title||'未命名案件'}`})))}).catch(()=>{if(active)message.error('案件候选加载失败')});return()=>{active=false}},[kind])
  const emptyColumns:TableColumnsType<any>=kind==='leave'?[{title:'请假开始日期'},{title:'请假结束日期'},{title:'请假小时'},{title:'请假类型'},{title:'备注'},{title:'操作'}]:kind==='matter'?[{title:'序号'},{title:'内容'},{title:'操作人'},{title:'操作日期'},{title:'操作'}]:[{title:'序号'},{title:'开始日期'},{title:'结束日期'},{title:'基本工资'},{title:'开庭比例提成'},{title:'开庭固定提成'},{title:'文书比例提成'},{title:'文书固定提成'},{title:'案源比例提成'},{title:'案源固定提成'},{title:'调查比例提成'},{title:'调查固定提成'},{title:'品管比例提成'},{title:'品管固定提成'},{title:'操作'}]
  const canMaintainCommission=kind!=='commission'||canManage
  if(!employeeId && (kind==='leave'||kind==='commission')){const notice=employeeSubrecordCreateMessage(employeeId);return <div className="employee-subrecord"><div className="subrecord-toolbar">{canMaintainCommission&&(kind!=='leave'||canManage)&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>{if(notice)message.info(notice)}}>新建</Button>}</div><Table rowKey="id" size="small" columns={emptyColumns} dataSource={[]} pagination={false}/><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={notice||'请先保存员工基本信息，再维护此页记录'}/></div>}
  const remove=async(id:number)=>{try{await api.delete(kind==='archive'?`/attachments/${id}`:`/hr/${employeeId}/subrecords/${id}`);message.success('删除成功');void load()}catch(error:any){message.error(error?.response?.data?.detail||'删除失败')}}
  const download=async(item:Attachment)=>{try{const response=await api.get(`/attachments/${item.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=url;anchor.download=item.original_name;anchor.click();URL.revokeObjectURL(url)}catch{message.error('文件下载失败')}}
  const [attachmentPreview,setAttachmentPreview]=useState<AttachmentPreview|null>(null)
  const preview=async(item:Attachment)=>{try{const {data}=await api.get(`/attachments/${item.id}/preview`);if(data.kind==='unsupported'){message.info(data.detail||'当前文件格式暂不支持在线预览，请下载后查看');return}if(data.kind==='image'||data.kind==='pdf'){const response=await api.get(`/attachments/${item.id}/download`,{responseType:'blob'});setAttachmentPreview({name:item.original_name,kind:data.kind,url:URL.createObjectURL(response.data)})}else setAttachmentPreview({name:item.original_name,kind:data.kind,text:data.text||''})}catch(error:any){message.error(error?.response?.data?.detail||'员工文档预览失败')}}
  const closePreview=()=>{if(attachmentPreview?.url)URL.revokeObjectURL(attachmentPreview.url);setAttachmentPreview(null)}
  const showEditor=(item?:Subrecord)=>{setEditing(item||null);const values:Record<string,any>=item?{...(item.data||{})}:kind==='commission'?{...commissionDefaults}:{};['start_date','end_date','operation_date'].forEach(key=>{if(values[key])values[key]=dayjs(values[key])});form.setFieldsValue(values);setOpen(true)}
  const save=async()=>{try{const values=await form.validateFields();['start_date','end_date','operation_date'].forEach(key=>{if(dayjs.isDayjs(values[key]))values[key]=values[key].format('YYYY-MM-DD')});if(editing)await api.patch(`/hr/${employeeId}/subrecords/${editing.id}`,{data:values});else await api.post(`/hr/${employeeId}/subrecords`,{kind,data:values});message.success(editing?'修改成功':'新增成功');setOpen(false);form.resetFields();void load()}catch(error:any){if(error?.errorFields)return;message.error(error?.response?.data?.detail||'保存失败')}}
  if(kind==='archive'){
    const columns:TableColumnsType<any>=[{title:'序号',width:65,render:(_v,_r,i)=>i+1},{title:'上传人',dataIndex:'uploader',width:120},{title:'文件名称',dataIndex:'original_name'},{title:'文档日期',dataIndex:'created_at',width:180,render:v=>dayjs(v).format('YYYY-MM-DD HH:mm')},{title:'查看',width:150,render:(_v,r)=><Space size={0}><Button type="link" icon={<EyeOutlined/>} onClick={()=>void preview(r)}>查看</Button><Button type="link" icon={<DownloadOutlined/>} onClick={()=>void download(r)}>下载</Button></Space>},{title:'操作',width:75,render:(_v,r)=>canManage?<Popconfirm title="确认删除该员工文档？" onConfirm={()=>void remove(r.id)}><Button type="link" danger>删除</Button></Popconfirm>:'只读'}]
    const upload=async()=>{if(!uploadFile){message.warning('请选择一个文件');return}if(!employeeId){message.info('请先保存员工基本资料');return}const data=new FormData();data.append('file',uploadFile);data.append('record_id',String(employeeId));data.append('category','员工档案');try{await api.post('/attachments',data,{headers:{'Content-Type':'multipart/form-data'}});message.success('员工文档上传成功');setUploadOpen(false);setUploadFile(null);void load()}catch(error:any){message.error(error?.response?.data?.detail||'上传失败')}}
    return <div className="employee-subrecord"><div className="subrecord-toolbar">{canManage&&<Button type="primary" icon={<UploadOutlined/>} onClick={()=>setUploadOpen(true)}>上传员工文档</Button>}</div><Table rowKey="id" size="small" loading={loading} columns={columns} dataSource={rows} pagination={{pageSize:15,showSizeChanger:true,pageSizeOptions:[10,15,20,50,100,200],showTotal:total=>`共 ${total} 条`}}/><Modal open={uploadOpen} title="上传员工文档" okText="上传" cancelText="取消" onOk={()=>void upload()} onCancel={()=>{setUploadOpen(false);setUploadFile(null)}} destroyOnHidden><Form.Item label="员工文档" required><Upload maxCount={1} beforeUpload={file=>{setUploadFile(file);return false}} onRemove={()=>{setUploadFile(null)}}><Button>选择一个文件</Button></Upload></Form.Item></Modal><Modal open={Boolean(attachmentPreview)} title={`在线查看：${attachmentPreview?.name||''}`} footer={<Button onClick={closePreview}>关闭</Button>} onCancel={closePreview} width={attachmentPreview?.kind==='pdf'?1000:760} destroyOnHidden>{attachmentPreview?.kind==='image'&&<img src={attachmentPreview.url} alt={attachmentPreview.name} style={{display:'block',maxWidth:'100%',maxHeight:'72vh',margin:'0 auto'}}/>}{attachmentPreview?.kind==='pdf'&&<iframe title={attachmentPreview.name} src={attachmentPreview.url} style={{width:'100%',height:'72vh',border:0}}/>}{(attachmentPreview?.kind==='text'||attachmentPreview?.kind==='docx')&&<pre style={{maxHeight:'70vh',overflow:'auto',margin:0,whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontFamily:'inherit',lineHeight:1.7}}>{attachmentPreview.text}</pre>}</Modal></div>
  }
  const action={title:'操作',width:130,render:(_v:any,r:Subrecord)=><Space size={0}><Button type="link" icon={<EditOutlined/>} onClick={()=>showEditor(r)}>编辑</Button><Popconfirm title="确认删除该记录？" onConfirm={()=>void remove(r.id)}><Button type="link" danger>删除</Button></Popconfirm></Space>}
  const readonlyAction={title:'操作',width:130,render:()=>'只读'}
  const commissionPair=(row:any,rate:string,fixed:string)=>`${row.data?.[rate]||0} / ${row.data?.[fixed]||0}`
  if(!employeeId && kind==='matter'){const notice=employeeSubrecordCreateMessage(employeeId);return <div className="employee-subrecord"><div className="subrecord-toolbar">{(kind!=='matter'||canManage)&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>{if(notice)message.info(notice)}}>新建</Button>}</div><Table rowKey="id" size="small" columns={emptyColumns} dataSource={[]} pagination={false}/><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={notice||'请先保存员工基本信息，再维护此页记录'}/></div>}
  const recordAction=kind==='leave'&&!canManage?readonlyAction:action
  const matterRecordAction=kind==='matter'&&!canManage?readonlyAction:recordAction
  const commissionRecordAction=kind==='commission'&&!canManage?readonlyAction:matterRecordAction
  const columns:TableColumnsType<any>=kind==='leave'?[{title:'请假开始',dataIndex:['data','start_date']},{title:'请假结束',dataIndex:['data','end_date']},{title:'小时',dataIndex:['data','hours']},{title:'类型',dataIndex:['data','leave_type']},{title:'备注',dataIndex:['data','remark']},recordAction]:kind==='matter'?[{title:'序号',width:65,render:(_v,_r,i)=>i+1},{title:'内容',dataIndex:['data','content']},{title:'操作人',dataIndex:'created_by',width:120},{title:'操作日期',dataIndex:['data','operation_date'],width:120},matterRecordAction]:[{title:'序号',width:65,render:(_v,_r,i)=>i+1},{title:'开始日期',dataIndex:['data','start_date']},{title:'结束日期',dataIndex:['data','end_date']},{title:'基本工资',dataIndex:['data','base_salary']},{title:'开庭比例提成',dataIndex:['data','hearing_rate']},{title:'开庭固定提成',dataIndex:['data','hearing_fixed']},{title:'文书比例提成',dataIndex:['data','document_rate']},{title:'文书固定提成',dataIndex:['data','document_fixed']},{title:'案源比例提成',dataIndex:['data','source_rate']},{title:'案源固定提成',dataIndex:['data','source_fixed']},{title:'调查比例提成',dataIndex:['data','investigation_rate']},{title:'调查固定提成',dataIndex:['data','investigation_fixed']},{title:'品管比例提成',dataIndex:['data','quality_rate']},{title:'品管固定提成',dataIndex:['data','quality_fixed']},commissionRecordAction]
  const leaveRows=kind==='leave'?rows.filter(row=>{const data=(row as Subrecord).data||{};const query=leaveQuery.toLocaleLowerCase();return !query||[data.start_date,data.end_date,data.leave_type,data.remark].some(value=>String(value||'').toLocaleLowerCase().includes(query))}):rows
  const leaveQueryPanel=kind==='leave'?<div className="subrecord-toolbar"><Input value={leaveQueryDraft} onChange={event=>setLeaveQueryDraft(event.target.value)} onPressEnter={()=>{setSubrecordPage(1);setLeaveQuery(leaveQueryDraft.trim())}} allowClear placeholder="请假类型、日期或备注" style={{width:260}}/><Button type="primary" onClick={()=>{setSubrecordPage(1);setLeaveQuery(leaveQueryDraft.trim())}}>查询</Button><Button onClick={()=>{setLeaveQueryDraft('');setLeaveQuery('');setSubrecordPage(1)}}>重置</Button></div>:null
  const title=kind==='leave'?'请假记录':kind==='matter'?'事项记录':'提成设定'
  const resolvePerformance=async()=>{if(!performanceCaseId){message.warning('请先选择案件');return}setPerformanceLoading(true);try{const {data}=await api.get(`/hr/${employeeId}/performance-for-case/${performanceCaseId}`);setResolvedPerformance(data)}catch(error:any){setResolvedPerformance(null);message.error(error?.response?.data?.detail||'适用提成方案查询失败')}finally{setPerformanceLoading(false)}}
  const performancePanel=kind==='commission'?<div className="subrecord-toolbar" style={{alignItems:'flex-start',flexWrap:'wrap'}}><Select style={{minWidth:320}} value={performanceCaseId} onChange={value=>{setPerformanceCaseId(value);setResolvedPerformance(null)}} allowClear showSearch optionFilterProp="label" placeholder="选择案件，查看该日期适用的提成方案" options={performanceCases}/><Button loading={performanceLoading} onClick={()=>void resolvePerformance()}>按案件查看适用提成</Button>{resolvedPerformance&&<span className="employee-account-tip">{resolvedPerformance.matched?`案件 ${resolvedPerformance.case_no}（${resolvedPerformance.case_date}）适用方案：${resolvedPerformance.performance?.data?.start_date||'—'} 至 ${resolvedPerformance.performance?.data?.end_date||'长期'}；基本工资 ${resolvedPerformance.performance?.data?.base_salary??0}`:`案件 ${resolvedPerformance.case_no}（${resolvedPerformance.case_date}）没有适用的提成方案`}</span>}</div>:null
  return <div className="employee-subrecord"><div className="subrecord-toolbar">{canMaintainCommission&&(kind!=='matter'||canManage)&&(kind!=='leave'||canManage)&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>showEditor()}>新建</Button>}</div>{leaveQueryPanel}{performancePanel}<Table rowKey="id" size="small" loading={loading} columns={columns} dataSource={leaveRows} pagination={{pageSize:15,current:subrecordPage,onChange:setSubrecordPage,showSizeChanger:true,pageSizeOptions:[10,15,20,50,100,200],showTotal:total=>`共 ${total} 条`}}/><Modal open={open} title={`${editing?'编辑':'新建'}${title}`} okText="保存" cancelText="取消" onOk={()=>void save()} onCancel={()=>{setOpen(false);form.resetFields()}} destroyOnHidden><Form form={form} layout="vertical">{kind==='leave'?<><Form.Item name="start_date" label="请假开始" rules={[{required:true}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="end_date" label="请假结束" rules={[{required:true}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="hours" label="小时" rules={[{required:true}]}><InputNumber min={0.5} step={0.5} style={{width:'100%'}}/></Form.Item><Form.Item name="leave_type" label="类型" rules={[{required:true}]}><Select options={['事假','病假','年假','婚假','产假','调休','其他'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="remark" label="备注"><Input.TextArea/></Form.Item></>:kind==='matter'?<><Form.Item name="content" label="内容" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item></>:<><div className="commission-form-grid"><Form.Item name="start_date" label="开始" rules={[{required:true}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item name="end_date" label="结束"><DatePicker style={{width:'100%'}}/></Form.Item>{[['base_salary','基本工资'],['hearing_rate','开庭比例'],['hearing_fixed','开庭固定'],['document_rate','文书比例'],['document_fixed','文书固定'],['source_rate','案源比例'],['source_fixed','案源固定'],['investigation_rate','调查比例'],['investigation_fixed','调查固定'],['quality_rate','品管比例'],['quality_fixed','品管固定']].map(([key,label])=><Form.Item key={key} name={key} label={label} initialValue={0}><InputNumber min={0} precision={2} style={{width:'100%'}}/></Form.Item>)}</div></>}</Form></Modal></div>
}

export default function HrCenterPage({initialView='hr-all'}:{initialView?:string}){
  const isNew=initialView==='hr-new'
  const [rows,setRows]=useState<Employee[]>([]),[loading,setLoading]=useState(false),[employeePage,setEmployeePage]=useState(1),[employeeTotal,setEmployeeTotal]=useState(0)
  const [accessRole,setAccessRole]=useState('')
  const [currentUsername,setCurrentUsername]=useState('')
  const [company,setCompany]=useState(companyName),[department,setDepartment]=useState(''),[username,setUsername]=useState(''),[name,setName]=useState(''),[mobile,setMobile]=useState(''),[enabled,setEnabled]=useState('')
  const [departments,setDepartments]=useState<{value:string;label:string}[]>([]),[positions,setPositions]=useState<{value:string;label:string}[]>([])
  const permissionRoleOptions=useMemo(()=>{
    const configuredRoles=new Set(positions.map(item=>item.value))
    const businessRoles=[...positions,...staffRoleOptions.filter(item=>!configuredRoles.has(item.value))]
    return [
      {label:'基础账号级别',options:baseRoleOptions},
      {label:'业务权限角色',options:businessRoles.map(item=>({value:businessRoleValue(item.value),label:item.label}))},
    ]
  },[positions])
  const [topTab,setTopTab]=useState(isNew?'new':'list'),[form]=Form.useForm()
  const accountType=Form.useWatch('account_type',form)||'员工账号'
  const [viewing,setViewing]=useState<Employee|null>(null),[detailTab,setDetailTab]=useState('basic'),[currentEmployeeId,setCurrentEmployeeId]=useState<number|undefined>()
  const [editingEmployee,setEditingEmployee]=useState<Employee|null>(null),[employeeEditForm]=Form.useForm(),[savingEmployee,setSavingEmployee]=useState(false)
  const editingSystemRole=Form.useWatch('system_role',employeeEditForm)||''
  const editingAccountType=Form.useWatch('account_type',employeeEditForm)||'员工账号'
  const [transitioningEmployee,setTransitioningEmployee]=useState<Employee|null>(null),[transitionForm]=Form.useForm(),[transitionSaving,setTransitionSaving]=useState(false)
  const [resettingEmployee,setResettingEmployee]=useState<Employee|null>(null),[passwordResetForm]=Form.useForm(),[passwordResetSaving,setPasswordResetSaving]=useState(false)
  const [deletingEmployee,setDeletingEmployee]=useState<Employee|null>(null),[deletionImpact,setDeletionImpact]=useState<DeletionImpact|null>(null),[deletionLoading,setDeletionLoading]=useState(false)
  const [selectedEmployeeIds,setSelectedEmployeeIds]=useState<number[]>([]),[batchDeletionImpact,setBatchDeletionImpact]=useState<any>(null),[batchDeleting,setBatchDeleting]=useState(false)
  const load=async(requestedPage=employeePage)=>{setLoading(true);try{
    const [profileResult,employeeResult]=await Promise.allSettled([api.get('/auth/me'),api.get('/hr/employees',{params:{page:requestedPage,page_size:15,company,department,username,name,mobile,enabled}})])
    const profile=profileResult.status==='fulfilled'?profileResult.value.data:null
    const role=profile?String(profile.role||''):''
    const currentLoginUsername=profile?String(profile.username||profile.user?.username||''):''
    setAccessRole(role)
    setCurrentUsername(currentLoginUsername)
    if(employeeResult.status==='rejected')throw employeeResult.reason
    const payload=employeeResult.value.data
    setRows((Array.isArray(payload)?payload:(payload?.items||[])) as Employee[])
    setEmployeeTotal(Number(payload.total||0))
    setEmployeePage(Number(payload.page||requestedPage))
  }catch{message.error('员工数据加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load();Promise.all([api.get('/hr/departments',{params:{active_only:true}}),api.get('/hr/job-roles',{params:{active_only:true}})]).then(([ds,rs])=>{setDepartments(ds.data.items.map((item:OrganizationOption)=>({value:item.name,label:item.name})));setPositions(rs.data.items.map((item:OrganizationOption)=>({value:item.name,label:item.name})))}).catch(()=>message.error('部门与职务加载失败'))},[])
  useEffect(()=>{setTopTab(isNew?'new':'list')},[isNew])
  useEffect(()=>{const target=consumeBusinessRecordDetailTarget('hr');if(!target)return;void (async()=>{try{const {data}=await api.get(`/records/${target.id}`);if(data.module!=='hr')throw new Error('关联记录不是员工档案');setViewing(data)}catch(error:any){message.error(error?.response?.data?.detail||error?.message||'员工详情加载失败')}})()},[])
  const resetNewEmployee=()=>{setCurrentEmployeeId(undefined);form.resetFields();form.setFieldsValue({serial_no:'',company:companyName,data_level:'公司',is_active:true,account_type:'员工账号',role:undefined,joined_at:dayjs(),contract_approval_enabled:false,...legacyEmployeeBasicDefaults})}
  useEffect(()=>{if(isNew)resetNewEmployee()},[isNew])

  const actionAccess=hrActionAccess(accessRole)
  const newEmployeeCanConfigureContractApproval=accountType==='员工账号'
  useEffect(()=>{if(!newEmployeeCanConfigureContractApproval&&form.getFieldValue('contract_approval_enabled'))form.setFieldValue('contract_approval_enabled',false)},[newEmployeeCanConfigureContractApproval,form])
  useEffect(()=>{if(!editingEmployee)return;if(!canConfigureContractApproval(editingSystemRole,editingEmployee.id,editingAccountType)&&employeeEditForm.getFieldValue('contract_approval_enabled'))employeeEditForm.setFieldValue('contract_approval_enabled',false)},[editingEmployee,editingSystemRole,editingAccountType,employeeEditForm])

  const openHrAdminNavigation=(page:string,params:Record<string,string>={})=>{if(!actionAccess.canManageAccount){message.error('仅系统管理员可以进入部门或审批关系管理');return}const search=new URLSearchParams({page,...params});window.location.href=`${window.location.pathname}?${search.toString()}`}
  const handleDepartmentFilterChange=(value?:string)=>{setDepartment(value||'');setSelectedEmployeeIds([]);setBatchDeletionImpact(null);setDeletingEmployee(null);setDeletionImpact(null);setEditingEmployee(null);employeeEditForm.resetFields()}
  const filtered=useMemo(()=>rows.filter(row=>{const d=row.data||{};return (!company||row.customer===company)&&(!department||row.department===department)&&(!username||String(d.username||row.owner).includes(username))&&(!name||row.title.includes(name))&&(!mobile||String(d.mobile||d.phone||'').includes(mobile))&&(!enabled||(d.is_active!==false?'是':'否')===enabled)}),[rows,company,department,username,name,mobile,enabled])
  const saveEmployee=async()=>{if(!actionAccess.canEditEmployee){message.error('仅系统管理员可以新建员工档案');return}if(currentEmployeeId){message.info('员工基本信息已保存，请通过员工列表的“修改”维护资料');return}const initialValue=form.getFieldsValue(true);const missing=firstMissingRequiredEmployeeField(initialValue);if(missing){Modal.info({title:'提示',content:missing.message,okText:'确定'});return}const value=await form.validateFields();const data={...value,staff_role:value.role,contract_approval_enabled:value.account_type==='员工账号'&&Boolean(value.contract_approval_enabled)};delete data.password;delete data.title;delete data.serial_no;delete data.company;delete data.department;delete data.role;delete data.username;for(const key of Object.keys(data)){if(dayjs.isDayjs(data[key]))data[key]=data[key].format('YYYY-MM-DD')}try{const {data:result}=await api.post('/hr/employees',{username:value.username||'',display_name:value.title,employee_no:value.serial_no,company:value.company,department:value.department,password:value.password||'',role:systemRoleOf(value.role),position:value.position,is_active:value.is_active,account_type:value.account_type,data});setCurrentEmployeeId(result.employee.id);message.success(value.account_type==='员工账号'?'员工档案与低权限登录账号已同步保存':'员工档案保存成功（未创建系统登录账号）');void load()}catch(error:any){const detail=error?.response?.data?.detail||'员工保存失败';if(detail==='登录账号已存在'||detail==='该登录账号已关联其他员工档案')form.setFields([{name:'username',errors:['用户名已存在，请使用未登记的用户名']}]);else if(detail==='中文姓名已存在')form.setFields([{name:'title',errors:['中文姓名已存在，请使用未登记的姓名']}]);message.error(detail)}}
  const openEmployeeEdit=async(row:Employee)=>{if(!actionAccess.canEditEmployee){message.error('仅系统管理员可以修改员工档案');return}try{const {data}=await api.get('/system/users',{params:{keyword:row.data.username||row.owner}});const account=data.items.find((item:any)=>item.username===(row.data.username||row.owner));const profileData={...(row.data||{}),...(account?.profile||{})};const dateValues=Object.fromEntries(employeeDateFields.map(key=>[key,profileData[key]?dayjs(profileData[key]):key==='joined_at'?dayjs():undefined]));employeeEditForm.resetFields();employeeEditForm.setFieldsValue({...profileData,...dateValues,display_name:account?.display_name||row.title,department:account?.department||row.department,system_role:profileData.permission_role?businessRoleValue(profileData.permission_role):account?.role||row.data.role||'user',staff_role:profileData.staff_role||profileData.position||'普通用户',position:profileData.position||'',email:profileData.email||account?.email||'',mobile:profileData.mobile||account?.mobile||'',extension:profileData.extension||profileData.office_phone||account?.office_phone||'',contract_approval_enabled:Boolean(account?.contract_approval_enabled??profileData.contract_approval_enabled),login_enabled:account?.is_active??row.data.is_active!==false});setEditingEmployee(row)}catch(error:any){message.error(error?.response?.data?.detail||'员工账号资料加载失败')}}
  const saveEmployeeEdit=async()=>{if(!editingEmployee)return;const value=await employeeEditForm.validateFields();const permissionRole=selectedBusinessRole(value.system_role);const effectiveSystemRole=permissionRole?systemRoleOf(permissionRole):value.system_role;const effectivePosition=permissionRole||value.position;const roleAllowsContractApproval=canConfigureContractApproval(value.system_role,editingEmployee.id);const canAssignContractApproval=roleAllowsContractApproval&&canConfigureContractApproval(value.system_role,editingEmployee.id,value.account_type);const editableData:Record<string,any>={...editingEmployee.data,username:value.username};for(const [key] of basicFields){if(['serial_no','username','password','company','title'].includes(key))continue;const formKey=key==='role'?'staff_role':key;const fieldValue=value[formKey];editableData[key]=dayjs.isDayjs(fieldValue)?fieldValue.format('YYYY-MM-DD'):fieldValue??''}editableData.staff_role=permissionRole||value.staff_role;editableData.position=effectivePosition;editableData.permission_role=permissionRole;editableData.contract_approval_enabled=canAssignContractApproval&&Boolean(value.contract_approval_enabled);setSavingEmployee(true);try{
    if(editingEmployee.id<0){
      await api.patch(`/system/users/${editingEmployee.data.system_user_id||-editingEmployee.id}`,{username:value.username,display_name:value.display_name,department:value.department,role:effectiveSystemRole,is_active:Boolean(value.login_enabled),profile:{...editableData,position:effectivePosition,email:value.email||'',mobile:value.mobile||'',office_phone:value.extension||'',joined_at:formatRequiredDate(value.joined_at,'加入日期'),left_at:value.left_at?.format('YYYY-MM-DD')||''}})
      message.success('系统账号资料已更新')
    }else{
      await api.patch(`/hr/employees/${editingEmployee.id}`,{username:value.username,display_name:value.display_name,department:value.department,role:effectiveSystemRole,position:effectivePosition,is_active:Boolean(value.login_enabled),email:value.email||'',mobile:value.mobile||'',office_phone:value.extension||'',joined_at:formatRequiredDate(value.joined_at,'加入日期'),left_at:value.left_at?.format('YYYY-MM-DD')||null,data:editableData})
      message.success('员工档案与登录账号已同步修改')
    }
    setEditingEmployee(null);await load()
  }catch(error:any){message.error(error?.response?.data?.detail||'员工修改失败')}finally{setSavingEmployee(false)}}
  const applyEmployeeLoginStatus=async(checked:boolean)=>{if(!editingEmployee)return;const previous=employeeEditForm.getFieldValue('login_enabled');employeeEditForm.setFieldValue('login_enabled',checked);setSavingEmployee(true);try{let updated:Employee={...editingEmployee,status:checked?'在职':editingEmployee.status,data:{...(editingEmployee.data||{}),is_active:checked}};if(editingEmployee.id<0){await api.patch(`/system/users/${editingEmployee.data.system_user_id||-editingEmployee.id}`,{is_active:checked});updated={...updated,status:checked?'在职':'停用'}}else{const {data}=await api.patch(`/hr/employees/${editingEmployee.id}/login-status`,{is_active:checked});updated=data.employee}setEditingEmployee(updated);setRows(prev=>prev.map(row=>row.id===updated.id?{...row,...updated,data:{...(row.data||{}),...(updated.data||{}),is_active:checked}}:row));if(viewing?.id===updated.id)setViewing(updated);message.success(checked?'登录账号已启用':'登录账号已停用，用户将无法登录')}catch(error:any){employeeEditForm.setFieldValue('login_enabled',previous);message.error(error?.response?.data?.detail||'登录账号启停失败')}finally{setSavingEmployee(false)}}
  const transitionOptions=(status:string):string[]=>hrTransitionOptions(status) as string[]
  const openTransition=(row:Employee)=>{if(!actionAccess.canProcessStatus){message.error('仅系统管理员或部门负责人可以办理人事状态');return}if(row.id<0){message.info('尚未建立人事档案的系统账号，请先补建员工档案后再办理人事状态');return}const options=transitionOptions(row.status);if(!options.length){message.info(`员工当前为“${row.status}”，暂无可办理的人事状态`);return}transitionForm.resetFields();transitionForm.setFieldsValue({to_status:options[0],effective_date:dayjs(),reason:'',handover_to:'',comment:''});setTransitioningEmployee(row)}
  const saveTransition=async()=>{if(!transitioningEmployee)return;const value=await transitionForm.validateFields();const reasonMessage=hrTransitionReasonMessage(value.to_status,value.reason);if(reasonMessage){message.error(reasonMessage);return}setTransitionSaving(true);try{await api.post(`/hr/${transitioningEmployee.id}/transition`,{...value,effective_date:formatRequiredDate(value.effective_date,'办理日期')});message.success('人事状态及关联登录账号已同步更新');setTransitioningEmployee(null);await load()}catch(error:any){message.error(error?.response?.data?.detail||'人事状态办理失败')}finally{setTransitionSaving(false)}}
  const openDeletionImpact=async(row:Employee)=>{if(!actionAccess.canDeleteEmployee){message.error('仅系统管理员可以删除员工档案');return}if(row.id<0){message.error('该登录账号尚未建立人事档案，请先在人事中心补建员工档案后再处理');return}setDeletionLoading(true);try{const {data}=await api.get(`/hr/employees/${row.id}/deletion-impact`);setDeletingEmployee(row);setDeletionImpact(data)}catch(error:any){message.error(error?.response?.data?.detail||'删除影响检查失败')}finally{setDeletionLoading(false)}}
  const deleteEmployee=async()=>{if(!deletingEmployee||!deletionImpact?.deletable)return;try{await api.delete(`/hr/employees/${deletingEmployee.id}`);if(viewing?.id===deletingEmployee.id)setViewing(null);message.success('员工档案及未被引用的关联登录账号已删除');setDeletingEmployee(null);setDeletionImpact(null);await load()}catch(error:any){const impact=error?.response?.data;if(impact?.blockers)setDeletionImpact(impact);else message.error(error?.response?.data?.detail||'删除员工失败')}}
  const openBatchDeletionImpact=async()=>{if(!actionAccess.canDeleteEmployee){message.error('仅系统管理员可以批量删除员工档案');return}try{const employee_ids=normalizeEmployeeIds(selectedEmployeeIds);setBatchDeleting(true);const {data}=await api.post('/hr/employees/batch-deletion-impact',{employee_ids});setBatchDeletionImpact(data)}catch(error:any){message.error(error?.response?.data?.detail||error?.message||'删除影响检查失败')}finally{setBatchDeleting(false)}}
  const deleteSelectedEmployees=async()=>{try{const employee_ids=normalizeEmployeeIds(selectedEmployeeIds);setBatchDeleting(true);await api.delete('/hr/employees/batch',{data:{employee_ids}});message.success('已删除所选员工档案');setBatchDeletionImpact(null);setSelectedEmployeeIds([]);await load()}catch(error:any){if(error?.response?.data?.blockers)setBatchDeletionImpact(error.response.data);else message.error(error?.response?.data?.detail||'删除员工失败')}finally{setBatchDeleting(false)}}
  const openDeletionBlockerCleanup = (blocker: DeletionImpact["blockers"][number], employee: Employee|null=deletingEmployee) => {
    const marker=blocker.records.find(record=>/^(leave|matter|commission)#/i.test(record))||''
    const tab=blocker.kind==='员工档案文件'?'archive':/^leave#/i.test(marker)||blocker.kind.includes('请假')?'leave':/^commission#/i.test(marker)||blocker.kind.includes('提成')?'commission':/^matter#/i.test(marker)||blocker.kind.includes('事项')?'matter':blocker.kind==='员工附属记录'?'matter':null
    if(!employee||!tab){message.info('请在员工管理或原业务流程处理该关联记录');return}
    setDetailTab(tab);setViewing(employee);setDeletingEmployee(null);setDeletionImpact(null);setBatchDeletionImpact(null)
  }
  const deletionBlockerLabel=(blocker:DeletionBlocker)=>blocker.kind.includes('登录账号')||blocker.kind.includes('系统用户')?'受保护登录账号':blocker.kind.includes('案件')?'案件业务关联':blocker.kind.includes('业务')?'业务关联':blocker.kind
  const isCleanableDeletionBlocker=(blocker:DeletionBlocker)=>blocker.kind==='员工附属记录'||blocker.kind==='员工档案文件'||blocker.kind.includes('请假')||blocker.kind.includes('事项')||blocker.kind.includes('提成')||blocker.records.some(record=>/^(leave|matter|commission)#/i.test(record))
  const deletionBlockerHint=(blocker:DeletionBlocker)=>blocker.kind.includes('登录账号')||blocker.kind.includes('系统用户')?'受保护登录账号请在员工管理中停用、重置或补齐档案后处理':blocker.kind.includes('案件')?'案件业务占用须回到案件业务流程处理':blocker.kind.includes('业务')?'业务关联须回到原业务流程处理':isCleanableDeletionBlocker(blocker)?'员工附属记录、员工档案文件可在 HR 员工页签去清理':'请按来源记录处理后再删除'
  const openBatchDeletionBlockerCleanup=(item:any,blocker:DeletionBlocker)=>{const employee=rows.find(row=>row.id===Number(item.employee_id));if(!employee){message.info('请在员工列表中查看该员工后处理关联记录');return}openDeletionBlockerCleanup(blocker,employee)}
  const openPasswordReset=(row:Employee)=>{if(!actionAccess.canManageAccount){message.error('仅系统管理员可以重置员工密码');return}const resettingUsername=row.data.username||row.owner;if(resettingUsername===currentUsername){message.error('不能重置当前登录账号密码');return}if(row.id<0){message.error('请先补建正式员工档案后再重置密码');return}passwordResetForm.resetFields();setResettingEmployee(row)}
  const savePasswordReset=async()=>{if(!resettingEmployee)return;const resettingUsername=resettingEmployee.data.username||resettingEmployee.owner;if(resettingUsername===currentUsername){message.error('不能重置当前登录账号密码');return}const value=await passwordResetForm.validateFields();try{setPasswordResetSaving(true);const {data}=await api.get('/system/users',{params:{keyword:resettingUsername}});const user=data.items.find((item:any)=>item.username===resettingUsername);if(!user)throw new Error('关联登录账号不存在');await api.post(`/system/users/${user.id}/reset-password`,{new_password:value.new_password});message.success('密码已重置，该员工下次登录必须修改密码');setResettingEmployee(null)}catch(error:any){message.error(error?.response?.data?.detail||error?.message||'重置密码失败')}finally{setPasswordResetSaving(false)}}

  const columns:TableColumnsType<Employee>=[
    {title:'序号',key:'no',width:65,render:(_v,_r,i)=>i+1},{title:'员工号',dataIndex:'serial_no',width:150},{title:'用户名',key:'username',width:120,render:(_v,r)=>r.data.username||r.owner},{title:'中文姓名',dataIndex:'title',width:110},{title:'所属部门',dataIndex:'department',width:150},{title:'所属公司',dataIndex:'customer',width:190},{title:'合同审批流程',key:'contractApproval',width:120,render:(_v,r)=>r.id>0&&r.data.contract_approval_enabled?'已配置':'未配置'},{title:'Email',key:'email',width:190,render:(_v,r)=>r.data.email||'—'},{title:'手机号码',key:'mobile',width:135,render:(_v,r)=>r.data.mobile||r.data.phone||'—'},{title:'固定电话',key:'office',width:125,render:(_v,r)=>r.data.office_phone||r.data.extension||'—'},{title:<Tooltip title="仅表示该员工关联的系统登录账号是否能访问系统；不等同于在职、离职等人事状态。">是否可用</Tooltip>,key:'active',width:100,render:(_v,r)=>r.data.is_active===false?'否':'是'},{title:'操作',key:'action',width:190,render:(_v,r)=><div className="employee-row-actions"><Button type="link" onClick={()=>setViewing(r)}>查看</Button>{actionAccess.canEditEmployee&&<Button type="link" icon={<EditOutlined/>} onClick={()=>void openEmployeeEdit(r)}>修改</Button>}{actionAccess.canProcessStatus&&<Button type="link" onClick={()=>openTransition(r)}>办理状态</Button>}{actionAccess.canManageAccount&&<Button type="link" onClick={()=>openPasswordReset(r)}>重置密码</Button>}{actionAccess.canDeleteEmployee&&<Button type="link" danger loading={deletionLoading} onClick={()=>void openDeletionImpact(r)}>删除</Button>}</div>},
  ]
  const rowSelection={selectedRowKeys:selectedEmployeeIds,onChange:(keys:React.Key[])=>setSelectedEmployeeIds(keys.map(Number).filter(id=>id>0)),getCheckboxProps:(row:Employee)=>({disabled:row.id<=0})}
  const listPanel=<><div className="hr-query"><label><span>公司</span><Select value={company} onChange={setCompany} options={[{value:companyName,label:companyName}]}/></label><label><span>部门</span><Select value={department} onChange={handleDepartmentFilterChange} allowClear placeholder="请选择" options={departments}/></label><label><span>用户名</span><Input value={username} onChange={e=>setUsername(e.target.value)} allowClear/></label><label><span>中文名</span><Input value={name} onChange={e=>setName(e.target.value)} allowClear/></label><label><span>手机号</span><Input value={mobile} onChange={e=>setMobile(e.target.value)} allowClear/></label><label><span>是否可用</span><Select value={enabled} onChange={setEnabled} options={[{value:'',label:'请选择'},{value:'是',label:'是'},{value:'否',label:'否'}]}/></label><Button type="primary" onClick={()=>{setEmployeePage(1);void load(1)}}>查询</Button>{actionAccess.canDeleteEmployee&&<Button danger loading={batchDeleting} onClick={()=>void openBatchDeletionImpact()}>删除选中</Button>}</div><Table className="employee-list-table" rowKey="id" rowSelection={actionAccess.canDeleteEmployee?rowSelection:undefined} size="small" loading={loading} columns={columns} dataSource={rows} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无数据"/>}} pagination={{current:employeePage,pageSize:15,total:employeeTotal,showTotal:total=>`共 ${total} 条`,onChange:(page)=>void load(page)}} scroll={{x:1710}}/></>

  const basicFields:[string,string,'input'|'select'|'date'|'number',any?][]=[
    ['serial_no','员工号*','input'],['username','用户名*','input'],['title','中文姓名*','input'],['role','角色*','select',staffRoleOptions],['password','密码*','input'],
    ['company','公司*','select',[{value:companyName,label:companyName}]],['department','部门*','select',departments],['position','职务*','select',positions],['data_level','数据级别*','select',dataLevels],
    ['account_type','账号类型','select',accountTypes],['id_no','身份证号','input'],['mobile','手机','input'],['english_level','英语等级','input'],['education','专业学历','input'],['extension','分机','input'],['native_place','籍贯','input'],['foreign_language','外语','input'],['graduation_date','毕业时间','date'],['social_security','社保情况','input'],['school','毕业学校','input'],['address','住址','input'],['id_address','身份证地址','input'],
    ['agent_qualification_no','代理人资格证号','input'],['agent_qualification_date','取得资格证日期','date'],['agent_practice_no','代理人执业证号','input'],['agent_practice_date','取得代理人执业证日期','date'],['professional_title','职称','input'],['social_position','社会职务','input'],['lawyer_license_no','律师执业证号','input'],['lawyer_license_date','取得律师职业证日期','date'],['political_status','政治面貌','select',employeeSelectOptions('political_status')],['training_date','上岗培训时间','date'],['agent_intern_start','代理人实习开始日期','date'],['agent_intern_end','代理人实习期结束日期','date'],['partner_start','合伙人开始日期','date'],['partner_end','合伙人结束日期','date'],['joined_at','加入日期','date'],['left_at','离职日期','date'],['job_title','职位','input'],['level','级别','input'],['annual_leave','年休剩余日数','number'],['source_rate','案源提成比','number'],['gender','性别','select',['男','女'].map(value=>({value,label:value}))],['marriage','婚姻状况','select',employeeSelectOptions('marriage')],['childbearing','生育状况','select',employeeSelectOptions('childbearing')],['writing_rate','撰稿提成比','number'],['contract_end','合同到期日','date'],['employment_status','在职情况','select',employeeSelectOptions('employment_status')],['email','Email','input'],['im','IM','input'],
  ]
  const employeeEditFields=basicFields.filter(([key])=>!['serial_no','username','password','company','title'].includes(key))
  const basic=<Form form={form} className="employee-form" labelCol={{flex:'120px'}} labelAlign="right" disabled={Boolean(currentEmployeeId)}> <div className="employee-form-grid">{basicFields.map(([key,label,type,options])=><Form.Item key={key} name={key} label={label.replace('*','')} rules={label.includes('*')?[{required:true,message:`请填写${label.replace('*','')}`}]:[]}>{type==='select'?<Select placeholder="请选择" options={options}/>:type==='date'?<DatePicker style={{width:'100%'}}/>:type==='number'?<InputNumber min={0} style={{width:'100%'}}/>:key==='password'?<Input.Password/>:<Input/>}</Form.Item>)}<Form.Item label="合同审批流程人员" name="contract_approval_enabled" valuePropName="checked"><Switch disabled={!newEmployeeCanConfigureContractApproval} checkedChildren="是" unCheckedChildren="否"/></Form.Item><Form.Item label="是否可用" name="is_active"><Radio.Group><Radio value={true}>是</Radio><Radio value={false}>否</Radio></Radio.Group></Form.Item></div>{accountType==='员工账号'&&<div className="employee-account-tip">合同审批资格按员工单独配置，不随“合伙人律师”等岗位自动获得；只有启用且在职的员工会进入合同审批人下拉框。</div>}<div className="employee-save"><Space><Button type="primary" disabled={Boolean(currentEmployeeId)} onClick={saveEmployee}>{currentEmployeeId?'基本信息已保存':'保存'}</Button>{currentEmployeeId&&<Button onClick={resetNewEmployee}>继续新建员工</Button>}</Space></div></Form>
  const employeeTabs=(employeeId?:number,basicNode?:ReactNode)=><Tabs activeKey={detailTab} onChange={setDetailTab} items={[...(basicNode?[{key:'basic',label:'基本信息',children:basicNode}]:[]),{key:'leave',label:'请假记录',children:<EmployeeSubrecords employeeId={employeeId} kind="leave" canManage={actionAccess.canProcessStatus}/>},{key:'matter',label:'事项记录',children:<EmployeeSubrecords employeeId={employeeId} kind="matter" canManage={actionAccess.canProcessStatus}/>},{key:'archive',label:'员工档案',children:<EmployeeSubrecords employeeId={employeeId} kind="archive" canManage={actionAccess.canProcessStatus}/>},{key:'commission',label:'提成设定',children:<EmployeeSubrecords employeeId={employeeId} kind="commission" canManage={actionAccess.canProcessStatus}/>}]}/>
  const newPanel=employeeTabs(currentEmployeeId,basic)
  const details=viewing?<Descriptions bordered size="small" column={2} items={[{key:'serial',label:'员工号',children:viewing.serial_no},{key:'username',label:'用户名',children:viewing.data.username||viewing.owner},{key:'name',label:'中文姓名',children:viewing.title},{key:'company',label:'所属公司',children:viewing.customer},{key:'department',label:'所属部门',children:viewing.department},{key:'position',label:'职务',children:viewing.data.position||'—'},{key:'contractApproval',label:'合同审批流程人员',children:viewing.data.contract_approval_enabled?'是':'否'},{key:'email',label:'Email',children:viewing.data.email||'—'},{key:'mobile',label:'手机号码',children:viewing.data.mobile||viewing.data.phone||'—'},{key:'office',label:'固定电话',children:viewing.data.office_phone||viewing.data.extension||'—'},{key:'joined',label:'加入日期',children:viewing.data.joined_at||'—'},{key:'status',label:'在职情况',children:viewing.status},{key:'active',label:'是否可用',children:viewing.data.is_active===false?'否':'是'}]}/>:null
  const detail=<Modal open={Boolean(viewing)} title={`员工查看：${viewing?.title||''}`} footer={null} width={1100} onCancel={()=>{setViewing(null);setDetailTab('basic')}} destroyOnHidden>{viewing&&(viewing.id<0?<><Descriptions bordered size="small" column={2} items={[{key:'serial',label:'员工号',children:viewing.serial_no},{key:'username',label:'用户名',children:viewing.data.username||viewing.owner},{key:'name',label:'中文姓名',children:viewing.title},{key:'company',label:'所属公司',children:viewing.customer},{key:'department',label:'所属部门',children:viewing.department},{key:'position',label:'职务',children:viewing.data.position||'—'},{key:'status',label:'账号状态',children:viewing.status},{key:'note',label:'说明',children:'该账号已纳入员工列表；补充完整人事资料后可维护请假、档案和提成记录。',span:2}]}/></>:employeeTabs(viewing.id,details))}</Modal>
  const editModal=<Modal open={Boolean(editingEmployee)} title={`员工完整资料修改：${editingEmployee?.serial_no||''}`} width={1120} styles={{body:{maxHeight:'70vh',overflowY:'auto'}}} okText="保存全部修改" cancelText="取消" confirmLoading={savingEmployee} onOk={()=>void saveEmployeeEdit()} onCancel={()=>setEditingEmployee(null)} destroyOnHidden><Form form={employeeEditForm} layout="vertical"><div className="employee-form-grid"><Form.Item name="username" label="用户名" rules={[{required:true,message:'请输入用户名'},{min:3,message:'用户名至少 3 位'},{pattern:/^[A-Za-z0-9._-]+$/,message:'只能包含字母、数字、点、下划线或短横线'}]}><Input autoComplete="off"/></Form.Item><Form.Item name="display_name" label="中文姓名" rules={[{required:true,message:'请输入中文姓名'}]}><Input/></Form.Item>{employeeEditFields.map(([key,label,type,options])=>{const name=key==='role'?'staff_role':key;const shownLabel=key==='role'?'人员角色':label.replace('*','');const rules:any[]=[];if(label.includes('*')||key==='joined_at')rules.push({required:true,message:`请填写${shownLabel}`});if(key==='email')rules.push({type:'email',message:'Email格式不正确'});return <Form.Item key={key} name={name} label={shownLabel} rules={rules}>{type==='select'?<Select placeholder="请选择" options={options}/>:type==='date'?<DatePicker style={{width:'100%'}}/>:type==='number'?<InputNumber min={0} style={{width:'100%'}}/>:<Input/>}</Form.Item>})}<Form.Item name="contract_approval_enabled" label="合同审批流程人员" valuePropName="checked"><Switch aria-disabled={!canConfigureContractApproval(editingSystemRole,editingEmployee?.id)} disabled={!canConfigureContractApproval(editingSystemRole,editingEmployee?.id,editingAccountType)} checkedChildren="是" unCheckedChildren="否"/>{!canConfigureContractApproval(editingSystemRole,editingEmployee?.id,editingAccountType)&&<div className="employee-account-tip">请先补建正式员工档案，且系统管理员或非员工账号不能配置为合同审批人。</div>}{actionAccess.canManageAccount&&<Button type="link" size="small" onClick={()=>openHrAdminNavigation('contract-approver-settings',{source:'hr',username:String(editingEmployee?.data?.username||editingEmployee?.owner||'')})}>审批关系</Button>}</Form.Item><Form.Item name="system_role" label="系统权限角色" rules={[{required:true,message:'请选择系统权限角色'}]}><Select showSearch optionFilterProp="label" placeholder="请选择基础级别或业务权限角色" options={permissionRoleOptions}/><div className="employee-account-tip">业务角色来自角色管理及旧系统角色目录；选择后会同步人员角色与职务，已配置角色同时应用其业务权限。</div></Form.Item><Form.Item name="login_enabled" label="登录账号启用" valuePropName="checked"><Switch checkedChildren="是" unCheckedChildren="否" loading={savingEmployee} onChange={(checked)=>void applyEmployeeLoginStatus(checked)}/><div className="employee-account-tip">关闭后该用户立即无法登录，已有登录会话也不能继续访问系统；员工离职或停用仍请使用“办理状态”。</div></Form.Item></div></Form></Modal>
  const transitionModal=<Modal open={Boolean(transitioningEmployee)} title={`办理人事状态：${transitioningEmployee?.serial_no||''}`} okText="确认办理" cancelText="取消" confirmLoading={transitionSaving} onOk={()=>void saveTransition()} onCancel={()=>setTransitioningEmployee(null)} destroyOnHidden><Form form={transitionForm} layout="vertical"><Form.Item label="目标状态" name="to_status" rules={[{required:true,message:'请选择目标状态'}]}><Select options={transitionOptions(transitioningEmployee?.status||'').map(value=>({value,label:value}))}/></Form.Item><Form.Item label="生效日期" name="effective_date" rules={[{required:true,message:'请选择生效日期'}]}><DatePicker style={{width:'100%'}}/></Form.Item><Form.Item label="办理原因" name="reason" rules={[{required:true,min:2,message:'请填写至少两个字符的办理原因'}]}><Input.TextArea rows={3}/></Form.Item><Form.Item label="交接给" name="handover_to"><Input placeholder="离职交接时填写接收账号或姓名"/></Form.Item><Form.Item label="办理说明" name="comment"><Input.TextArea rows={2}/></Form.Item></Form></Modal>
  const passwordResetModal=<Modal open={Boolean(resettingEmployee)} title={`重置密码：${resettingEmployee?.title||''}`} okText="确认重置" cancelText="取消" confirmLoading={passwordResetSaving} onOk={()=>void savePasswordReset()} onCancel={()=>setResettingEmployee(null)} destroyOnHidden><Form form={passwordResetForm} layout="vertical"><Form.Item name="new_password" label="新密码" rules={[{required:true,message:'请输入新密码'},{min:8,message:'密码至少 8 位'}]}><Input.Password autoComplete="new-password"/></Form.Item><div className="employee-account-tip">重置后该员工下次登录必须修改密码；当前管理员账号不能在此处重置。</div></Form></Modal>
  const deletionModal=<Modal open={Boolean(deletingEmployee&&deletionImpact)} title={`删除影响检查：${deletingEmployee?.serial_no||''}`} okText="确认删除" cancelText="取消" okButtonProps={{danger:true,disabled:!deletionImpact?.deletable}} onOk={()=>void deleteEmployee()} onCancel={()=>{setDeletingEmployee(null);setDeletionImpact(null)}} destroyOnHidden>{deletionImpact?.deletable?<p>未发现关联记录，可删除员工档案及未被引用的关联登录账号。</p>:<><p>当前不能删除。请先处理以下关联记录：</p><ul>{(deletionImpact?.blockers||[]).map(blocker=>{const cleanable=isCleanableDeletionBlocker(blocker);return <li key={blocker.kind}>{deletionBlockerLabel(blocker)}：{blocker.count} 条（{blocker.records.join('、')||'未返回标识'}）<span className="employee-account-tip"> {deletionBlockerHint(blocker)}</span>{cleanable&&<Button type="link" size="small" onClick={()=>openDeletionBlockerCleanup(blocker)}>去清理</Button>}</li>})}</ul><p className="employee-account-tip">员工附属记录和员工档案文件可直接进入当前员工的对应维护页签；受保护登录账号请在员工管理中停用、重置或补齐档案后处理；业务关联、案件等引用仅作说明，仍须在原业务流程中处理。</p></>}</Modal>
  const batchDeletionModal=<Modal open={Boolean(batchDeletionImpact)} title="删除选中员工影响检查" okText="确认删除" cancelText="取消" confirmLoading={batchDeleting} okButtonProps={{danger:true,disabled:!batchDeletionImpact?.deletable}} onOk={()=>void deleteSelectedEmployees()} onCancel={()=>setBatchDeletionImpact(null)} destroyOnHidden>{batchDeletionImpact?.deletable?<p>所选员工均未被引用，确认后将原子删除。</p>:<><p>当前不能删除；请先处理以下员工的关联记录：</p><ul>{(batchDeletionImpact?.blockers||[]).map((item:any)=><li key={item.employee_id}>{item.employee_no}<ul>{item.blockers.map((blocker:DeletionBlocker)=><li key={blocker.kind}>{deletionBlockerLabel(blocker)}：{blocker.count} 条（{blocker.records.join('、')||'未返回标识'}）<span className="employee-account-tip"> {deletionBlockerHint(blocker)}</span>{isCleanableDeletionBlocker(blocker)&&<Button type="link" size="small" onClick={()=>openBatchDeletionBlockerCleanup(item,blocker)}>去清理</Button>}</li>)}</ul></li>)}</ul><p className="employee-account-tip">员工附属记录和员工档案文件可进入员工维护页签去清理；受保护登录账号请在员工管理中停用、重置或补齐档案后处理；业务关联、案件等引用须回到对应业务流程处理。</p></>}</Modal>
  if(!isNew)return <><Card className="panel hr-panel" title="员工列表">{listPanel}</Card>{detail}{editModal}{transitionModal}{passwordResetModal}{deletionModal}{batchDeletionModal}</>
  return <><Card className="panel hr-panel" title="员工信息"><Tabs activeKey={topTab} onChange={setTopTab} items={[{key:'new',label:'员工新建',children:newPanel},{key:'list',label:'员工列表',children:listPanel}]}/></Card>{detail}{editModal}{transitionModal}{passwordResetModal}{deletionModal}{batchDeletionModal}</>
}
