import { useEffect, useRef, useState } from "react";
import { Button, Card, DatePicker, Descriptions, Drawer, Form, Input, Modal, Select, Space, Table, Tag, message } from "antd";
import type { TableColumnsType } from "antd";
import { api } from "./api";
import { formatRequiredDate } from "./formSafety";
import dayjs from "dayjs";

type IprCase={id:number;serial_no:string;title:string;customer:string;status:string;data:Record<string,any>};
type Official={id:number;serial_no:string;title:string;customer:string;status:string;description:string;data:Record<string,any>};
type Attachment={id:number;original_name:string;size:number;uploader:string;download_url:string};
type ImportBatch={id:number;source_filename:string;status:string;total_count:number;error_count:number;imported_count:number;created_by:string;created_at:string};
type ImportCandidate={id:number;row_no:number;ipr_case_id:number|null;application_no:string;official_type:string;official_no:string;received_date:string|null;due_date:string|null;errors:string[];status:string;official_record_id:number|null};
type ChecklistItem={id:number;batch_id:number;source_filename:string;application_no:string;official_type:string;invention_title:string;official_no:string;electronic_date:string|null;download_status:string;system_status:string;case_id:number|null;case_no:string;imported_at:string|null;errors:string[];candidate_status:string;official_record_id:number|null};
const colors:Record<string,string>={"待校验":"gold","待转发":"blue","已转发":"cyan","已办结":"green"};
const patentTypes=["专利申请受理通知书","费用减缓审批通知","受理通知书纸件","发明专利申请初步审查合格通知书","发明专利申请公布通知书","发明专利申请进入实质审查阶段通知书","实质审查请求期限届满前通知","手续合格通知书","补正通知","第一次审查意见通知书（发明）","第一次审查意见通知书（实用/外观）","第N次审查意见通知书","办理手续补正通知书","驳回决定","恢复权利请求审批通知书","办理恢复权利手续补正通知","缴费通知书","专利证书通知","视为撤回通知书","视为放弃取得专利权通知书","视为未要求优先权通知","视为未提出通知","授权及缴纳授权费通知","授权通知纸件","复审请求受理通知书","专利权终止","其他官文"];
const trademarkTypes=["商标注册证书","商标注册申请受理通知书","异议受理通知书","异议决定书","争议受理通知书","复审决定书","异议答辩通知书","商标续展注册证明","不予受理通知书","商标驳回通知书","商标部分驳回通知书","商标复审受理通知","商标核准转让证明","商标注册申请初步审定公告通知书","商标注册申请补正通知书","许可备案通知书","商标变更证明","商标变更申请补正通知书","视为撤回通知书","通知商标续展","商标转让受理通知书","商标转让申请补正通知书","撤销连续三年不使用注册商标受理通知书","注册商标连续三年不使用撤销申请的决定","关于提供注册商标使用证据的通知","商标评审案件答辩通知书","商标无效宣告请求裁定书","其他官文"];

export default function IprOfficialFilePage(){
  const [items,setItems]=useState<Official[]>([]),[total,setTotal]=useState(0),[cases,setCases]=useState<IprCase[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[keyword,setKeyword]=useState(""),[status,setStatus]=useState(""),[viewMode,setViewMode]=useState<"active"|"history"|"checklist">("active"),[checkItems,setCheckItems]=useState<ChecklistItem[]>([]),[selected,setSelected]=useState<React.Key[]>([]),[detail,setDetail]=useState<Official|null>(null),[attachments,setAttachments]=useState<Attachment[]>([]);
  const [batches,setBatches]=useState<ImportBatch[]>([]),[batchOpen,setBatchOpen]=useState(false),[batchId,setBatchId]=useState<number>(),[candidates,setCandidates]=useState<ImportCandidate[]>([]),[candidateSelected,setCandidateSelected]=useState<React.Key[]>([]),[candidateEditor,setCandidateEditor]=useState<ImportCandidate|null>(null),[candidateFile,setCandidateFile]=useState<File|null>(null);
  const [profile,setProfile]=useState<{role?:string}>({}),[form]=Form.useForm(),[candidateForm]=Form.useForm(),fileRef=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null);
  const selectedCaseId=Form.useWatch("ipr_case_id",form);
  const selectedCase=cases.find(item=>item.id===selectedCaseId);
  const officialTypeOptions=(selectedCase?.data.case_kind==="商标"?trademarkTypes:patentTypes).map(value=>({value,label:value}));
  const load=async()=>{setLoading(true);try{if(viewMode==="checklist"){const {data}=await api.get<{items:ChecklistItem[];total:number}>("/ipr/official-files/checklist",{params:{keyword}});setCheckItems(data.items||[]);setTotal(data.total||0);setSelected([]);return}const {data}=await api.get("/ipr/official-files",{params:{keyword,record_status:viewMode==="history"?"已办结":status,page_size:100}});setItems(data.items||[]);setTotal(data.total||0);setSelected([])}catch(e:any){message.error(e?.response?.data?.detail||"知识产权官文加载失败")}finally{setLoading(false)}};
  const loadBatches=async()=>{try{const {data}=await api.get<{items:ImportBatch[]}>("/ipr/official-files/import-batches");setBatches(data.items||[])}catch(e:any){message.error(e?.response?.data?.detail||"官文导入批次加载失败")}};
  const loadCandidates=async(id:number)=>{try{const {data}=await api.get<{items:ImportCandidate[]}>(`/ipr/official-files/import-batches/${id}/candidates`);setCandidates(data.items||[]);setCandidateSelected([])}catch(e:any){message.error(e?.response?.data?.detail||"官文候选行加载失败")}};
  useEffect(()=>{void load();void loadBatches();void api.get<{items:IprCase[]}>("/ipr/cases",{params:{record_status:"在办",page_size:100}}).then(({data})=>setCases(data.items||[])).catch(()=>setCases([]));void api.get<{role?:string}>("/auth/me").then(({data})=>setProfile(data)).catch(()=>setProfile({}))},[viewMode]);
  const start=()=>{form.resetFields();setFile(null);setOpen(true)};
  const upload=async()=>{try{const value=await form.validateFields();if(!file){message.warning("请选择官文原件");return}const data=new FormData();data.append("file",file);data.append("ipr_case_id",String(value.ipr_case_id));data.append("official_type",value.official_type);data.append("official_no",value.official_no||"");if(value.received_date)data.append("received_date",formatRequiredDate(value.received_date,"接收日期"));if(value.due_date)data.append("due_date",formatRequiredDate(value.due_date,"办理期限"));data.append("remark",value.remark||"");await api.post("/ipr/official-files",data);message.success("知识产权官文已导入，等待校验");setOpen(false);void load()}catch(e:any){if(!e?.errorFields)message.error(e?.response?.data?.detail||"官文导入失败")}};
  const action=async(row:Official,action:"validate"|"transmit"|"complete")=>{try{await api.post(`/ipr/official-files/${row.id}/${action}`,{comment:""});message.success("操作成功");if(detail?.id===row.id)setDetail(null);void load()}catch(e:any){message.error(e?.response?.data?.detail||"操作失败")}};
  const batchAction=async(action:"validate"|"transmit"|"complete")=>{try{if(!selected.length){message.warning("请先选择需要办理的官文");return}await api.post(`/ipr/official-files/actions/batch/${action}`,{official_ids:selected,comment:""});message.success("批量操作成功");void load()}catch(e:any){message.error(e?.response?.data?.detail||"批量操作失败")}};
  const openDetail=async(row:Official)=>{setDetail(row);try{const {data}=await api.get("/attachments",{params:{record_id:row.id}});setAttachments(data.items||[])}catch{setAttachments([])}};
  const download=async(item:Attachment)=>{try{const res=await api.get(`/attachments/${item.id}/download`,{responseType:"blob"});const url=URL.createObjectURL(res.data);const a=document.createElement("a");a.href=url;a.download=item.original_name;a.click();URL.revokeObjectURL(url)}catch{message.error("官文原件下载失败")}};
  const downloadBlob=async(path:string,params:Record<string,unknown>,filename:string,failed:string)=>{try{const response=await api.get(path,{params,responseType:"blob"});const url=URL.createObjectURL(response.data);const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.click();URL.revokeObjectURL(url)}catch(error:any){message.error(error?.response?.data?.detail||failed)}};
  const exportExcel=()=>void downloadBlob("/ipr/official-files/export/excel",{record_status:viewMode==="history"?"已办结":status,keyword},"知识产权官文清单.xls","官文清单导出失败");
  const exportChecklist=()=>void downloadBlob("/ipr/official-files/checklist/export/excel",{keyword},"知识产权官文检查清单.xls","官文检查清单导出失败");
  const downloadSelectedZip=()=>{if(!selected.length){message.warning("请先选择需要打包下载的官文");return}void downloadBlob("/ipr/official-files/download-zip",{ids:selected.join(",")},"知识产权官文原件.zip","官文原件打包下载失败")};
  const historyBatchAction=async(action:"business-process"|"service-process")=>{try{if(!selected.length){message.warning("请先选择需要标记的历史官文");return}await api.post(`/ipr/official-files/history/actions/batch/${action}`,{official_ids:selected,comment:"页面批量标记历史处理"});message.success(action==="business-process"?"已标记历史官文业务处理":"已标记历史官文流程处理");void load()}catch(e:any){message.error(e?.response?.data?.detail||"历史官文批量处理失败")}};
  const uploadCandidateFile=async()=>{try{if(!candidateFile){message.warning("请选择 UTF-8 CSV 源文件");return}const data=new FormData();data.append("file",candidateFile);const {data:created}=await api.post<ImportBatch>("/ipr/official-files/import-batches",data);message.success(`已解析 ${created.total_count} 行，请逐行确认后再导入`);setCandidateFile(null);setBatchId(created.id);await loadBatches();await loadCandidates(created.id)}catch(e:any){message.error(e?.response?.data?.detail||"官文候选解析失败")}};
  const openBatch=async(id:number)=>{setBatchId(id);await loadCandidates(id)};
  const editCandidate=(candidate:ImportCandidate)=>{setCandidateEditor(candidate);candidateForm.setFieldsValue({application_no:candidate.application_no,official_type:candidate.official_type,official_no:candidate.official_no,received_date:candidate.received_date?dayjs(candidate.received_date):undefined,due_date:candidate.due_date?dayjs(candidate.due_date):undefined,ipr_case_id:candidate.ipr_case_id||undefined})};
  const saveCandidate=async()=>{if(!candidateEditor)return;try{const value=await candidateForm.validateFields();const payload={application_no:value.application_no||"",official_type:value.official_type||"",official_no:value.official_no||"",received_date:value.received_date?formatRequiredDate(value.received_date,"收发文日"):null,due_date:value.due_date?formatRequiredDate(value.due_date,"办理期限"):null};await api.patch(`/ipr/official-files/import-candidates/${candidateEditor.id}`,payload);if(value.ipr_case_id)await api.post(`/ipr/official-files/import-candidates/${candidateEditor.id}/match`,{ipr_case_id:value.ipr_case_id,comment:"页面人工匹配"});message.success("候选行已保存并重新校验");setCandidateEditor(null);if(batchId)await loadCandidates(batchId)}catch(e:any){if(!e?.errorFields)message.error(e?.response?.data?.detail||"候选行保存失败")}};
  const confirmCandidates=async()=>{try{if(!batchId||!candidateSelected.length){message.warning("请勾选已确认的候选行");return}const {data}=await api.post<{created:number}>(`/ipr/official-files/import-batches/${batchId}/confirm`,{candidate_ids:candidateSelected,comment:"页面确认导入"});message.success(`已生成 ${data.created} 条正式官文`);await Promise.all([load(),loadBatches(),loadCandidates(batchId)])}catch(e:any){message.error(e?.response?.data?.detail||"候选确认导入失败")}};
  const columns:TableColumnsType<Official>=[
    {title:"官文编号",dataIndex:"serial_no",width:190,ellipsis:true,render:(value,row)=><Button type="link" onClick={()=>void openDetail(row)}>{value}</Button>},{title:"官文类型",dataIndex:"title",width:200,ellipsis:true},{title:"官文号",width:150,render:(_,r)=>r.data.official_no||"—"},{title:"关联案件",width:190,ellipsis:true,render:(_,r)=><Button type="link" onClick={()=>window.location.assign(`/?page=${r.data.case_kind==="商标"?"ipr-trademark":"ipr-patent"}&record_id=${r.data.ipr_case_id}`)}>{r.data.ipr_case_no||"—"}</Button>},{title:"类型",width:80,render:(_,r)=>r.data.case_kind||"—"},{title:"业务处理",width:100,render:(_,r)=><Tag>{r.data.business_process_status||"未处理"}</Tag>},{title:"流程处理",width:100,render:(_,r)=><Tag color="blue">{r.data.service_process_status||"未处理"}</Tag>},{title:"状态",width:100,render:(_,r)=><Tag color={colors[r.status]||"default"}>{r.status}</Tag>},
    {title:"操作",fixed:"right",width:180,render:(_,r)=><Space size={0}>{r.status==="待校验"&&["admin","manager"].includes(profile.role||"")&&<Button type="link" onClick={()=>action(r,"validate")}>校验</Button>}{r.status==="待转发"&&<Button type="link" onClick={()=>action(r,"transmit")}>转发</Button>}{r.status==="已转发"&&<Button type="link" onClick={()=>action(r,"complete")}>办结</Button>}</Space>}
  ];
  const checklistColumns:TableColumnsType<ChecklistItem>=[{title:"申请号/不受理编号",dataIndex:"application_no",width:180,ellipsis:true},{title:"通知书名称",dataIndex:"official_type",width:200,ellipsis:true},{title:"发明创造名称",dataIndex:"invention_title",width:180,ellipsis:true},{title:"发文序列号",dataIndex:"official_no",width:150,ellipsis:true},{title:"电子发文日",dataIndex:"electronic_date",width:110,render:value=>value||"—"},{title:"下载状态",dataIndex:"download_status",width:120},{title:"系统状态",dataIndex:"system_status",width:110,render:value=><Tag>{value}</Tag>},{title:"案号",dataIndex:"case_no",width:170,render:(value,row)=>row.case_id?<Button type="link" onClick={()=>window.location.assign(`/?page=ipr-patent&record_id=${row.case_id}`)}>{value||"—"}</Button>:"—"},{title:"入库时间",dataIndex:"imported_at",width:170,ellipsis:true},{title:"错误消息",dataIndex:"errors",width:260,render:value=>value?.length?<Space wrap>{value.map((error:string)=><Tag color="red" key={error}>{error}</Tag>)}</Space>:"—"}];
  const switchView=(mode:"active"|"history"|"checklist")=>{setViewMode(mode);setSelected([]);setStatus("")};
  return <div className="page-shell"><Card title="知识产权官文" extra={<Space wrap><Button type={viewMode==="active"?"primary":"default"} onClick={()=>switchView("active")}>当前官文</Button><Button type={viewMode==="history"?"primary":"default"} onClick={()=>switchView("history")}>历史已办结</Button><Button type={viewMode==="checklist"?"primary":"default"} onClick={()=>switchView("checklist")}>检查清单</Button>{viewMode!=="checklist"&&<Select value={status} onChange={setStatus} style={{width:120}} options={[{value:"",label:"全部状态"},...Object.keys(colors).map(value=>({value,label:value}))]}/>}<Input value={keyword} onChange={e=>setKeyword(e.target.value)} onPressEnter={load} placeholder={viewMode==="checklist"?"申请号、通知书名称、发文号":"官文编号、官文号、案件编号"} allowClear style={{width:230}}/><Button onClick={load}>查询</Button>{viewMode==="checklist"?<><Button onClick={()=>{setBatchOpen(true);void loadBatches()}}>上传检查清单</Button><Button onClick={exportChecklist}>导出检查清单（Excel）</Button></>:viewMode==="history"?<><Button onClick={exportExcel}>导出Excel</Button><Button onClick={downloadSelectedZip} disabled={!selected.length}>打包下载（ZIP）</Button><Button onClick={()=>void historyBatchAction("business-process")} disabled={!selected.length}>标记业务已处理</Button><Button onClick={()=>void historyBatchAction("service-process")} disabled={!selected.length}>标记流程已处理</Button></>:<><Button onClick={exportExcel}>导出Excel</Button><Button onClick={downloadSelectedZip} disabled={!selected.length}>打包下载（ZIP）</Button><Button onClick={()=>void batchAction("validate")} disabled={!selected.length||!['admin','manager'].includes(profile.role||'')}>批量校验</Button><Button onClick={()=>void batchAction("transmit")} disabled={!selected.length}>批量转发</Button><Button onClick={()=>void batchAction("complete")} disabled={!selected.length}>批量办结</Button><Button onClick={()=>{setBatchOpen(true);void loadBatches()}}>候选导入</Button><Button type="primary" onClick={start}>单份导入</Button></>}</Space>}>{viewMode==="checklist"?<Table rowKey="id" size="small" loading={loading} columns={checklistColumns} dataSource={checkItems} scroll={{x:1650}} pagination={{pageSize:20,total,showTotal:t=>`共 ${t} 条`}}/>:<Table rowKey="id" rowSelection={{selectedRowKeys:selected,onChange:setSelected}} size="small" loading={loading} columns={columns} dataSource={items} scroll={{x:1370}} pagination={{pageSize:20,total,showTotal:t=>`共 ${t} 条`}}/>}</Card>
    <Modal open={open} width={680} title="导入知识产权官文" onCancel={()=>setOpen(false)} onOk={upload} okText="导入并进入校验"><Form form={form} layout="vertical"><Form.Item name="ipr_case_id" label="关联在办知识产权案件" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={cases.map(item=>({value:item.id,label:`${item.serial_no}｜${item.data.case_kind}｜${item.title}｜${item.customer}`}))}/></Form.Item><div className="form-grid"><Form.Item name="official_type" label="官文类型" rules={[{required:true}]}><Select showSearch options={officialTypeOptions}/></Form.Item><Form.Item name="official_no" label="官文号"><Input/></Form.Item><Form.Item name="received_date" label="接收日期"><DatePicker style={{width:"100%"}}/></Form.Item><Form.Item name="due_date" label="办理期限"><DatePicker style={{width:"100%"}}/></Form.Item></div><Form.Item label="官文原件" required><input ref={fileRef} type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.zip,.txt,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<div>{file.name}</div>}</Form.Item><Form.Item name="remark" label="说明"><Input.TextArea rows={3}/></Form.Item></Form></Modal>
    <Modal open={batchOpen} width={1180} title="官文候选导入与确认" footer={null} onCancel={()=>setBatchOpen(false)}><Space direction="vertical" size="middle" style={{width:"100%"}}><Card size="small" title="第一步：上传候选 CSV"><Space wrap><input type="file" accept=".csv,text/csv" onChange={e=>setCandidateFile(e.target.files?.[0]||null)}/><Button type="primary" onClick={()=>void uploadCandidateFile()}>解析为候选行</Button><span>只解析不入库；请逐行修正、匹配并确认后才生成正式官文。</span></Space></Card><Space wrap><span>历史批次：</span><Select value={batchId} placeholder="选择一个可见批次" style={{width:430}} onChange={value=>void openBatch(value)} options={batches.map(item=>({value:item.id,label:`#${item.id}｜${item.source_filename}｜${item.status}｜${item.imported_count}/${item.total_count} 已导入`}))}/><Button onClick={()=>void loadBatches()}>刷新批次</Button><Button type="primary" disabled={!batchId||!candidateSelected.length} onClick={()=>void confirmCandidates()}>确认选中候选并生成正式官文</Button></Space><Table rowKey="id" size="small" rowSelection={{selectedRowKeys:candidateSelected,onChange:setCandidateSelected,getCheckboxProps:row=>({disabled:row.status!=="待确认"})}} dataSource={candidates} scroll={{x:1100}} pagination={false} columns={[{title:"行",dataIndex:"row_no",width:60},{title:"申请号",dataIndex:"application_no",width:180,ellipsis:true},{title:"官文类型",dataIndex:"official_type",width:190,ellipsis:true},{title:"官文号",dataIndex:"official_no",width:150,ellipsis:true},{title:"关联案件",width:220,render:(_,row:ImportCandidate)=>{const item=cases.find(value=>value.id===row.ipr_case_id);return item?`${item.serial_no}｜${item.title}`:"未匹配";}},{title:"问题",width:260,render:(_,row:ImportCandidate)=>row.errors?.length?<Space wrap>{row.errors.map(error=><Tag color="red" key={error}>{error}</Tag>)}</Space>:<Tag color="green">可确认</Tag>},{title:"状态",dataIndex:"status",width:90,render:value=><Tag color={value==="已导入"?"green":value==="待确认"?"blue":"gold"}>{value}</Tag>},{title:"操作",fixed:"right",width:100,render:(_,row:ImportCandidate)=>row.status!=="已导入"?<Button type="link" onClick={()=>editCandidate(row)}>修正/匹配</Button>:<Button type="link" disabled>已导入</Button>}]}/></Space></Modal>
    <Modal open={!!candidateEditor} title={candidateEditor?`修正候选行 ${candidateEditor.row_no}`:"修正候选行"} onCancel={()=>setCandidateEditor(null)} onOk={()=>void saveCandidate()} okText="保存并校验"><Form form={candidateForm} layout="vertical"><Form.Item name="application_no" label="申请号/注册号" rules={[{required:true,message:"请填写申请号/注册号"}]}><Input/></Form.Item><Form.Item name="official_type" label="官文类型" rules={[{required:true,message:"请填写官文类型"}]}><Input/></Form.Item><div className="form-grid"><Form.Item name="official_no" label="官文号"><Input/></Form.Item><Form.Item name="ipr_case_id" label="人工匹配在办案件"><Select allowClear showSearch optionFilterProp="label" options={cases.map(item=>({value:item.id,label:`${item.serial_no}｜${item.data.case_kind}｜${item.title}`}))}/></Form.Item><Form.Item name="received_date" label="收发文日"><DatePicker style={{width:"100%"}}/></Form.Item><Form.Item name="due_date" label="办理期限"><DatePicker style={{width:"100%"}}/></Form.Item></div></Form></Modal>
    <Drawer width={680} title={detail?`知识产权官文详情：${detail.serial_no}`:"知识产权官文详情"} open={!!detail} onClose={()=>setDetail(null)}>{detail&&<><Descriptions size="small" bordered column={2} items={[{key:"type",label:"官文类型",children:detail.title},{key:"status",label:"状态",children:detail.status},{key:"no",label:"官文号",children:detail.data.official_no||"—"},{key:"case",label:"关联案件",children:<Button type="link" onClick={()=>window.location.assign(`/?page=${detail.data.case_kind==="商标"?"ipr-trademark":"ipr-patent"}&record_id=${detail.data.ipr_case_id}`)}>{detail.data.ipr_case_no||"—"}</Button>},{key:"received",label:"接收日期",children:detail.data.received_date||"—"},{key:"due",label:"办理期限",children:detail.data.due_date||"—"},{key:"remark",label:"说明",children:detail.description||"—",span:2}]}/><Card size="small" title="官文原件" style={{marginTop:16}}>{attachments.length?attachments.map(item=><Button key={item.id} type="link" onClick={()=>void download(item)}>{item.original_name}</Button>):"未找到官文原件"}</Card><Space style={{marginTop:16}}>{detail.status==="待校验"&&['admin','manager'].includes(profile.role||'')&&<Button type="primary" onClick={()=>void action(detail,"validate")}>校验</Button>}{detail.status==="待转发"&&<Button type="primary" onClick={()=>void action(detail,"transmit")}>转发</Button>}{detail.status==="已转发"&&<Button type="primary" onClick={()=>void action(detail,"complete")}>办结</Button>}</Space></>}</Drawer>
  </div>
}
