import { useEffect, useState } from "react";
import { Button, Descriptions, Drawer, Form, Input, Modal, Popconfirm, Space, Switch, Table, Tabs, Upload, message } from "antd";
import { DownloadOutlined, PlusOutlined, UploadOutlined } from "@ant-design/icons";
import { api } from "./api";

type License = { id: number; original_name: string };
type Firm = { id:number; code:string; name:string; registered_address:string; business_address:string; detail_address:string; postal_code:string; phone:string; fax:string; email:string; organization_code:string; company_code:string; country:string; is_active:boolean; default_contact_id:number|null; license:License|null };
type Contact = { id:number; name:string; address:string; postal_code:string; phone:string; fax:string; email:string; is_active:boolean; is_default:boolean; created_by?:string; created_at?:string };

const firmFields: [keyof Firm, string][] = [["code","律所编号"],["name","律所名称"],["registered_address","注册地址"],["business_address","营业地址"],["detail_address","详细地址"],["postal_code","邮编"],["phone","律所电话"],["fax","传真"],["email","邮箱"],["organization_code","组织机构代码"],["company_code","统一社会信用代码"],["country","国家/地区"]];

export default function LawFirmPage(){
  const [firms,setFirms]=useState<Firm[]>([]),[loading,setLoading]=useState(false),[keyword,setKeyword]=useState(""),[editing,setEditing]=useState<Firm|null>(null),[detail,setDetail]=useState<Firm|null>(null),[contacts,setContacts]=useState<Contact[]>([]),[contactEdit,setContactEdit]=useState<Contact|null>(null),[detailTab,setDetailTab]=useState("contacts");
  const [firmForm]=Form.useForm(),[contactForm]=Form.useForm();
  const load=async()=>{setLoading(true);try{const {data}=await api.get("/law-firms",{params:{keyword,include_inactive:true}});setFirms(data.items||[])}catch(error:any){message.error(error?.response?.data?.detail||"律所档案加载失败")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const openDetail=async(firm:Firm)=>{try{const [firmResponse,contactsResponse]=await Promise.all([api.get(`/law-firms/${firm.id}`),api.get(`/law-firms/${firm.id}/contacts`)]);setDetail(firmResponse.data);setContacts(contactsResponse.data.items||[])}catch(error:any){message.error(error?.response?.data?.detail||"律所档案加载失败")}};
  const openFirm=(firm?:Firm)=>{firmForm.resetFields();firmForm.setFieldsValue(firm||{country:"中国",is_active:true});setEditing(firm||({id:0} as Firm))};
  const saveFirm=async()=>{const values=await firmForm.validateFields();try{if(editing?.id)await api.put(`/law-firms/${editing.id}`,values);else await api.post("/law-firms",values);message.success("律所档案已保存");setEditing(null);void load()}catch(error:any){message.error(error?.response?.data?.detail||"保存失败")}};
  const deleteFirm=async(firm:Firm)=>{try{await api.delete(`/law-firms/${firm.id}`);if(detail?.id===firm.id)setDetail(null);message.success("律所档案已删除");void load()}catch(error:any){message.error(error?.response?.data?.detail||"删除失败")}};
  const loadDetail=async()=>{if(detail)await openDetail(detail)};
  const openContacts=(firm:Firm)=>{void openDetail(firm);setDetailTab("contacts")};
  const openContact=(item?:Contact)=>{contactForm.resetFields();contactForm.setFieldsValue(item||{is_active:true});setContactEdit(item||({id:0} as Contact))};
  const saveContact=async()=>{if(!detail)return;const values=await contactForm.validateFields();try{if(contactEdit?.id)await api.put(`/law-firms/${detail.id}/contacts/${contactEdit.id}`,values);else await api.post(`/law-firms/${detail.id}/contacts`,values);message.success("联系人已保存");setContactEdit(null);void loadDetail()}catch(error:any){message.error(error?.response?.data?.detail||"联系人保存失败")}};
  const setDefault=async(item:Contact)=>{if(!detail)return;try{await api.post(`/law-firms/${detail.id}/contacts/${item.id}/default`);message.success("已设为默认联系人");void loadDetail()}catch(error:any){message.error(error?.response?.data?.detail||"设置失败")}};
  const toggleContactActive=async(item:Contact)=>{if(!detail)return;try{await api.put(`/law-firms/${detail.id}/contacts/${item.id}`,{name:item.name,address:item.address,postal_code:item.postal_code,phone:item.phone,fax:item.fax,email:item.email,is_active:!item.is_active});message.success(item.is_active?"联系人已停用":"联系人已启用");void loadDetail()}catch(error:any){message.error(error?.response?.data?.detail||"联系人状态更新失败")}};
  const uploadLicense=async(option:any)=>{if(!detail)return;try{const form=new FormData();form.append("file",option.file as Blob);await api.post(`/law-firms/${detail.id}/license`,form,{headers:{"Content-Type":"multipart/form-data"}});option.onSuccess?.({});message.success("营业执照已替换");await load();await loadDetail()}catch(error:any){option.onError?.(error);message.error(error?.response?.data?.detail||"上传失败")}};
  const downloadLicense=async()=>{if(!detail)return;try{const response=await api.get(`/law-firms/${detail.id}/license/download`,{responseType:"blob"});const url=URL.createObjectURL(response.data);const link=document.createElement("a");link.href=url;link.download=detail.license?.original_name||"营业执照";link.click();URL.revokeObjectURL(url)}catch(error:any){message.error(error?.response?.data?.detail||"下载失败")}};
  return <div className="panel system-focused"><div className="system-toolbar"><Input allowClear placeholder="编号、名称、电话或邮箱" value={keyword} onChange={event=>setKeyword(event.target.value)} onPressEnter={()=>void load()} style={{width:280}}/><Button type="primary" onClick={()=>void load()}>查询</Button><Button icon={<PlusOutlined/>} onClick={()=>openFirm()}>新建律所</Button></div><Table rowKey="id" loading={loading} dataSource={firms} scroll={{x:1900}} pagination={{pageSize:15}} columns={[{title:"编号",dataIndex:"code",width:130},{title:"律所名称",dataIndex:"name",width:220,render:(value,row)=><Button type="link" onClick={()=>void openDetail(row)}>{value}</Button>},{title:"注册地址",dataIndex:"registered_address",width:240,ellipsis:true},{title:"邮编",dataIndex:"postal_code",width:110},{title:"电话",dataIndex:"phone",width:150},{title:"传真",dataIndex:"fax",width:120},{title:"邮箱",dataIndex:"email",width:200},{title:"国家地区",dataIndex:"country",width:120},{title:"机构代码",dataIndex:"organization_code",width:150},{title:"公司代码",dataIndex:"company_code",width:170},{title:"营业地址",dataIndex:"business_address",width:240,ellipsis:true},{title:"状态",width:100,render:(_,row)=>row.is_active?"有效":"停用"},{title:"操作",width:300,fixed:"right",render:(_,row)=><Space><Button type="link" onClick={()=>void openDetail(row)}>详情</Button><Button type="link" onClick={()=>openContacts(row)}>联系人</Button><Button type="link" onClick={()=>openFirm(row)}>编辑</Button><Popconfirm title="删除律所档案" description="将同时删除联系人和营业执照，且不可恢复。" okText="删除" cancelText="取消" onConfirm={()=>void deleteFirm(row)}><Button type="link" danger>删除</Button></Popconfirm></Space>}]} />
    <Modal open={Boolean(editing)} title={editing?.id?"修改律所档案":"新建律所档案"} width={760} onOk={()=>void saveFirm()} onCancel={()=>setEditing(null)} destroyOnHidden><Form form={firmForm} layout="vertical"><div className="form-grid">{firmFields.map(([key,label])=><Form.Item key={String(key)} name={key} label={label} rules={key==="code"||key==="name"?[{required:true,message:`请填写${label}`}]:undefined}><Input /></Form.Item>)}<Form.Item name="is_active" label="有效状态" valuePropName="checked"><Switch checkedChildren="有效" unCheckedChildren="停用"/></Form.Item></div></Form></Modal>
    <Drawer open={Boolean(detail)} width={920} title={`律所档案：${detail?.name||""}`} onClose={()=>setDetail(null)}>{detail&&<><Descriptions bordered size="small" column={2} items={firmFields.map(([key,label])=>({key:String(key),label,children:String(detail[key]||"—")})).concat([{key:"status",label:"状态",children:detail.is_active?"有效":"停用"}])}/><Tabs style={{marginTop:18}} activeKey={detailTab} onChange={setDetailTab} items={[{key:"contacts",label:"联系人",children:<><div className="system-toolbar"><Button type="primary" icon={<PlusOutlined/>} onClick={()=>openContact()}>新建联系人</Button></div><Table rowKey="id" size="small" dataSource={contacts} pagination={false} scroll={{x:1300}} columns={[{title:"序号",dataIndex:"id",width:60},{title:"姓名",dataIndex:"name"},{title:"联系电话",dataIndex:"phone"},{title:"邮箱",dataIndex:"email"},{title:"联系地址",dataIndex:"address",ellipsis:true},{title:"邮编",dataIndex:"postal_code"},{title:"传真",dataIndex:"fax"},{title:"创建人",dataIndex:"created_by",render:(value:string)=>value||"—"},{title:"创建时间",dataIndex:"created_at",render:(value:string)=>value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"—"},{title:"状态",render:(_,row)=>row.is_active?"有效":"停用"},{title:"默认",render:(_,row)=>row.is_default?"是":"否"},{title:"操作",render:(_,row)=><Space><Button type="link" disabled={row.is_default||!row.is_active} onClick={()=>void setDefault(row)}>设为默认</Button><Button type="link" onClick={()=>openContact(row)}>编辑</Button><Button type="link" onClick={()=>void toggleContactActive(row)}>{row.is_active?"停用":"启用"}</Button></Space>}]} /></>},{key:"license",label:"营业执照",children:<Space direction="vertical"><span>{detail.license?.original_name||"尚未上传营业执照"}</span><Space><Upload accept=".jpg,.jpeg,.png,.gif" showUploadList={false} customRequest={uploadLicense}><Button icon={<UploadOutlined/>}>上传/替换营业执照</Button></Upload>{detail.license&&<Button icon={<DownloadOutlined/>} onClick={()=>void downloadLicense()}>下载营业执照</Button>}</Space><span>支持 JPG、PNG、GIF；重新上传会替换旧文件并保留审计记录。</span></Space>}]}/></>}</Drawer>
    <Modal open={Boolean(contactEdit)} title={contactEdit?.id?"修改联系人":"新建联系人"} onOk={()=>void saveContact()} onCancel={()=>setContactEdit(null)} destroyOnHidden><Form form={contactForm} layout="vertical"><Form.Item name="name" label="联系人" rules={[{required:true,message:"请输入联系人"}]}><Input/></Form.Item><Form.Item name="address" label="联系地址" rules={[{required:true,message:'请输入联系地址'}]}><Input/></Form.Item><Form.Item name="postal_code" label="邮编" rules={[{required:true,message:'请输入邮编'}]}><Input/></Form.Item><Form.Item name="phone" label="联系电话" rules={[{required:true,message:'请输入联系电话'}]}><Input/></Form.Item><Form.Item name="fax" label="传真" rules={[{required:true,message:'请输入传真'}]}><Input/></Form.Item><Form.Item name="email" label="邮箱" rules={[{required:true,message:'请输入邮箱'}]}><Input/></Form.Item><Form.Item name="is_active" label="有效状态" valuePropName="checked"><Switch checkedChildren="有效" unCheckedChildren="停用"/></Form.Item></Form></Modal>
  </div>
}