import {useEffect, useState} from 'react'
import {Alert, Button, Card, Checkbox, Empty, Form, Input, InputNumber, message, Modal, Popconfirm, Space, Switch, Table, Tag} from 'antd'
import type {TableColumnsType} from 'antd'
import {DeleteOutlined, EditOutlined, PlusOutlined} from '@ant-design/icons'
import {api} from './api'
import './organization-center.css'

type Department={id:number;code:string;name:string;manager:string;sort_order:number;is_active:boolean}
type JobRole={id:number;code:string;name:string;permissions:string[];description:string;sort_order:number;is_active:boolean}
const permissionGroups=[
  {name:'客户与合同',items:['客户查看','客户新建','客户修改','客户分配','客户回收/恢复','客户共享','利益冲突检索','合同查看','合同新建','合同修改','合同提交审批','合同审批','合同归档']},
  {name:'案件与调查',items:['案件查看','案件新建','案件分配','案件承办','案件进展维护','开庭排期','案件办结','案件归档申请','案件归档审核','调查任务发起','调查任务办理','线索审核','公证管理','证据管理']},
  {name:'任务与文档',items:['任务查看','任务派发','任务接受','任务协作','任务交接','任务完成确认','收文登记','发文登记','文书模板维护','业务附件上传/下载','智能文档生成','智能文档人工确认']},
  {name:'财务与用印',items:['费用查看','费用申请','费用审批','回款登记','回款分配','付款登记','付款审批','开票申请','开票审批','退款办理','内部结算','对账','用印申请','用印审批','印章管理']},
  {name:'组织与系统',items:['员工查看','员工新建','员工修改','部门管理','岗位角色管理','仓库查看','仓库出入库','报表查看','报表导出','系统用户管理','系统权限配置','系统参数配置','审计日志查看']},
]
const permissionLabels=new Map(permissionGroups.flatMap(group=>group.items.map(item=>[item,group.name])))

export default function OrganizationCenterPage({initialView='hr-departments'}:{initialView?:string}){
  const rolesView=initialView==='hr-roles'
  const [departments,setDepartments]=useState<Department[]>([]),[roles,setRoles]=useState<JobRole[]>([]),[loading,setLoading]=useState(false)
  const [open,setOpen]=useState(false),[editingDepartment,setEditingDepartment]=useState<Department|null>(null),[editingRole,setEditingRole]=useState<JobRole|null>(null)
  const [departmentForm]=Form.useForm(),[roleForm]=Form.useForm()
  const load=async()=>{setLoading(true);try{const [departmentResult,roleResult]=await Promise.all([api.get('/hr/departments'),api.get('/hr/job-roles')]);setDepartments(departmentResult.data.items);setRoles(roleResult.data.items)}catch(error:any){message.error(error?.response?.data?.detail||'组织数据加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const start=(row?:Department|JobRole)=>{if(rolesView){const role=row as JobRole|undefined;setEditingRole(role||null);setEditingDepartment(null);roleForm.resetFields();roleForm.setFieldsValue(role||{permissions:[],sort_order:roles.length+1,is_active:true})}else{const department=row as Department|undefined;setEditingDepartment(department||null);setEditingRole(null);departmentForm.resetFields();departmentForm.setFieldsValue(department||{sort_order:departments.length+1,is_active:true})}setOpen(true)}
  const save=async()=>{try{if(rolesView){const value=await roleForm.validateFields();if(editingRole)await api.patch(`/hr/job-roles/${editingRole.id}`,value);else await api.post('/hr/job-roles',value)}else{const value=await departmentForm.validateFields();if(editingDepartment)await api.patch(`/hr/departments/${editingDepartment.id}`,value);else await api.post('/hr/departments',value)}message.success('保存成功');setOpen(false);void load()}catch(error:any){message.error(error?.response?.data?.detail||'保存失败')}}
  const removeDepartment=async(row:Department)=>{try{await api.delete(`/hr/departments/${row.id}`);message.success('删除成功');void load()}catch(error:any){message.error(error?.response?.data?.detail||'删除失败')}}
  const removeRole=async(row:JobRole)=>{try{await api.delete(`/hr/job-roles/${row.id}`);message.success('删除成功');void load()}catch(error:any){message.error(error?.response?.data?.detail||'删除失败')}}
  const departmentColumns:TableColumnsType<Department>=[{title:'序号',key:'no',width:70,render:(_v,_r,i)=>i+1},{title:'部门名称',dataIndex:'name'},{title:'部门代码',dataIndex:'code',width:150},{title:'部门负责人',dataIndex:'manager',width:130,render:value=>value||'—'},{title:'排序',dataIndex:'sort_order',width:75},{title:'可用',dataIndex:'is_active',width:75,render:value=>value?'是':'否'},{title:'操作',key:'action',width:130,render:(_v,row)=><Space size={0}><Button type="link" icon={<EditOutlined/>} onClick={()=>start(row)}>修改</Button><Popconfirm title="确认删除该部门？" onConfirm={()=>removeDepartment(row)}><Button type="link" danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}]
  const roleColumns:TableColumnsType<JobRole>=[{title:'序号',key:'no',width:70,render:(_v,_r,i)=>i+1},{title:'角色名称',dataIndex:'name',width:180},{title:'角色代码',dataIndex:'code',width:130},{title:'角色权限',dataIndex:'permissions',render:(values:string[])=><Space size={[4,4]} wrap>{values?.length?values.map(value=><Tag key={value} color={permissionLabels.has(value)?'blue':'default'}>{value}</Tag>):'—'}</Space>},{title:'权限数',dataIndex:'permissions',width:80,render:(values:string[])=>values?.length||0},{title:'可用',dataIndex:'is_active',width:75,render:value=>value?'是':'否'},{title:'操作',key:'action',width:130,render:(_v,row)=><Space size={0}><Button type="link" icon={<EditOutlined/>} onClick={()=>start(row)}>修改</Button><Popconfirm title="确认删除该角色？" onConfirm={()=>removeRole(row)}><Button type="link" danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}]
  const title=rolesView?'角色列表':'部门列表',button=rolesView?'新增角色':'新增部门'
  const emptyContent=<div className="organization-empty"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无数据"/>{rolesView&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>start()}>新增角色</Button>}</div>
  return <><Card className="panel organization-panel" title={title}><div className="organization-action"><Button type="primary" icon={<PlusOutlined/>} onClick={()=>start()}>{button}</Button></div>{rolesView?<Table rowKey="id" size="small" loading={loading} columns={roleColumns} dataSource={roles} locale={{emptyText:emptyContent}} pagination={{pageSize:20,showTotal:total=>`共 ${total} 条`}}/>:<Table rowKey="id" size="small" loading={loading} columns={departmentColumns} dataSource={departments} locale={{emptyText:emptyContent}} pagination={{pageSize:20,showTotal:total=>`共 ${total} 条`}}/>}</Card><Modal open={open} title={`${editingDepartment||editingRole?'修改':'新增'}${rolesView?'角色':'部门'}`} okText="保存" cancelText="取消" onOk={save} onCancel={()=>setOpen(false)} destroyOnHidden width={rolesView?980:650}>{rolesView?<Form form={roleForm} layout="vertical"><div className="organization-form-grid"><Form.Item label="角色名称" name="name" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="角色代码" name="code" rules={[{required:true}]}><Input/></Form.Item><Form.Item className="span-2"><Alert type="info" showIcon title="按具体业务动作配置岗位权限；登录后的菜单、数据范围和敏感字段仍由系统角色权限统一控制。"/></Form.Item><Form.Item className="span-2" label="业务动作权限" name="permissions"><Checkbox.Group className="job-permission-matrix">{permissionGroups.map(group=><section key={group.name}><b>{group.name}</b><div>{group.items.map(item=><Checkbox key={item} value={item}>{item}</Checkbox>)}</div></section>)}</Checkbox.Group></Form.Item><Form.Item label="排序号" name="sort_order" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item label="是否可用" name="is_active" valuePropName="checked"><Switch/></Form.Item><Form.Item className="span-2" label="说明" name="description"><Input.TextArea rows={2}/></Form.Item></div></Form>:<Form form={departmentForm} layout="vertical"><div className="organization-form-grid"><Form.Item label="部门名称" name="name" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="部门代码" name="code" rules={[{required:true}]}><Input/></Form.Item><Form.Item label="部门负责人" name="manager"><Input/></Form.Item><Form.Item label="排序号" name="sort_order" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item label="是否可用" name="is_active" valuePropName="checked"><Switch/></Form.Item></div></Form>}</Modal></>
}
