"""稳定导出请求数据契约，定义按业务领域维护。"""

from app.api_schemas.agents import (
    DifyRequest as DifyRequest,
    CaseAgentProposedAction as CaseAgentProposedAction,
    CaseAgentMessageInput as CaseAgentMessageInput,
    UserAgentSkillInput as UserAgentSkillInput,
    UserAgentSkillUpdate as UserAgentSkillUpdate,
    CaseAgentDecisionInput as CaseAgentDecisionInput,
    AgentDocumentInput as AgentDocumentInput,
    AgentDocumentUpdate as AgentDocumentUpdate,
    AgentDocumentConfirmInput as AgentDocumentConfirmInput,
)
from app.api_schemas.records import (
    RecordInput as RecordInput,
    RecordUpdate as RecordUpdate,
    TransitionInput as TransitionInput,
)
from app.api_schemas.official_documents import (
    DocumentTransitionInput as DocumentTransitionInput,
    OfficialDocumentProcessInput as OfficialDocumentProcessInput,
    OfficialDocumentReceiptDateInput as OfficialDocumentReceiptDateInput,
    OfficialDocumentDeleteInput as OfficialDocumentDeleteInput,
    OfficialDocumentBatchCaseIdsInput as OfficialDocumentBatchCaseIdsInput,
    OfficialOutgoingCreateInput as OfficialOutgoingCreateInput,
    OfficialOutgoingUpdateInput as OfficialOutgoingUpdateInput,
    OfficialOutgoingReviewInput as OfficialOutgoingReviewInput,
    OfficialOutgoingRollbackInput as OfficialOutgoingRollbackInput,
    OfficialOutgoingSubmitInput as OfficialOutgoingSubmitInput,
    OfficialOutgoingBatchInput as OfficialOutgoingBatchInput,
)
from app.api_schemas.organization import (
    HrTransitionInput as HrTransitionInput,
    HrEmployeeBatchDeleteInput as HrEmployeeBatchDeleteInput,
    HrSubrecordInput as HrSubrecordInput,
    HrPerformanceInput as HrPerformanceInput,
    HrSubrecordUpdate as HrSubrecordUpdate,
    DepartmentInput as DepartmentInput,
    DepartmentUpdate as DepartmentUpdate,
    JobRoleInput as JobRoleInput,
    JobRoleUpdate as JobRoleUpdate,
    JobRolePermissionUpdate as JobRolePermissionUpdate,
    HrEmployeeUpdateInput as HrEmployeeUpdateInput,
    HrEmployeeLoginStatusInput as HrEmployeeLoginStatusInput,
    HrEmployeeContractApprovalStatusInput as HrEmployeeContractApprovalStatusInput,
    HrEmployeeSealApprovalStatusInput as HrEmployeeSealApprovalStatusInput,
    HrEmployeeCreateInput as HrEmployeeCreateInput,
    LawFirmInput as LawFirmInput,
    LawFirmContactInput as LawFirmContactInput,
)
from app.api_schemas.warehouse import (
    WarehouseBorrowInput as WarehouseBorrowInput,
    WarehouseReturnInput as WarehouseReturnInput,
    WarehouseReturnConfirmInput as WarehouseReturnConfirmInput,
    WarehouseScrapInput as WarehouseScrapInput,
    WarehouseGoodsListSearchCondition as WarehouseGoodsListSearchCondition,
    WarehouseGoodsListInput as WarehouseGoodsListInput,
    WarehouseEvidenceInput as WarehouseEvidenceInput,
    WarehouseEvidenceCheckInInput as WarehouseEvidenceCheckInInput,
    WarehouseEvidenceCheckOutInput as WarehouseEvidenceCheckOutInput,
    WarehouseEvidenceRecheckInInput as WarehouseEvidenceRecheckInInput,
    WarehouseEvidenceDestroyInput as WarehouseEvidenceDestroyInput,
    EvidenceCreateInput as EvidenceCreateInput,
    EvidenceRegistrationItem as EvidenceRegistrationItem,
    EvidenceBatchRegistrationInput as EvidenceBatchRegistrationInput,
    EvidenceUpdateInput as EvidenceUpdateInput,
)
from app.api_schemas.finance import (
    ReceivableInput as ReceivableInput,
    ReceivePaymentInput as ReceivePaymentInput,
    CaseAssistedFeeCreateInput as CaseAssistedFeeCreateInput,
    CaseAssistedFeeUpdateInput as CaseAssistedFeeUpdateInput,
    CaseAssistedFeeConfirmInput as CaseAssistedFeeConfirmInput,
    CaseBatchFeeContractInput as CaseBatchFeeContractInput,
    CaseBatchFeeInput as CaseBatchFeeInput,
    RefundCaseFeeBatchItemInput as RefundCaseFeeBatchItemInput,
    RefundCaseFeeBatchCreateInput as RefundCaseFeeBatchCreateInput,
    FinanceFeeCommissionDetailInput as FinanceFeeCommissionDetailInput,
    FinanceFeeInput as FinanceFeeInput,
    FinanceFeeUpdateInput as FinanceFeeUpdateInput,
    JarFeeInput as JarFeeInput,
    JarFeeStatusInput as JarFeeStatusInput,
    CaseFeeBatchUpdateInput as CaseFeeBatchUpdateInput,
    FinanceFeeInformInput as FinanceFeeInformInput,
    FinanceFeeArrivalInput as FinanceFeeArrivalInput,
    FinanceFeeInformLinksInput as FinanceFeeInformLinksInput,
    CaseCommissionCreateItemInput as CaseCommissionCreateItemInput,
    CaseCommissionBatchInput as CaseCommissionBatchInput,
    CaseCommissionPreviewInput as CaseCommissionPreviewInput,
    FinanceActionInput as FinanceActionInput,
    FinancePaymentTypeCreateInput as FinancePaymentTypeCreateInput,
    FinancePaymentCancelInput as FinancePaymentCancelInput,
    FinancePaymentRollbackInput as FinancePaymentRollbackInput,
    FinanceSettlementMarkInput as FinanceSettlementMarkInput,
    FinanceFeeReviewInput as FinanceFeeReviewInput,
    FinanceFeeBatchReviewInput as FinanceFeeBatchReviewInput,
    FinancePaymentPackagePreviewInput as FinancePaymentPackagePreviewInput,
    FinancePaymentPackageCreateInput as FinancePaymentPackageCreateInput,
    FinancePaymentPackageUpdateInput as FinancePaymentPackageUpdateInput,
    FinancePaymentPackageWriteoffInput as FinancePaymentPackageWriteoffInput,
    InvoiceApplicationInput as InvoiceApplicationInput,
    InvoiceIssueInput as InvoiceIssueInput,
    InvoiceVoidInput as InvoiceVoidInput,
    InvoiceNumberChangeInput as InvoiceNumberChangeInput,
    InvoiceDateChangeInput as InvoiceDateChangeInput,
    FinanceReviewInput as FinanceReviewInput,
    LitigationRefundInput as LitigationRefundInput,
    RefundCompleteInput as RefundCompleteInput,
    RefundAmountUpdateInput as RefundAmountUpdateInput,
    RefundBatchStatusInput as RefundBatchStatusInput,
    CaseFeeRefundLogInput as CaseFeeRefundLogInput,
    FinanceTransactionInput as FinanceTransactionInput,
    FinanceWriteoffInput as FinanceWriteoffInput,
    IncomingPaymentInput as IncomingPaymentInput,
    IncomingPaymentClaimInput as IncomingPaymentClaimInput,
    IncomingPaymentSettlementItem as IncomingPaymentSettlementItem,
    IncomingPaymentAllocationItem as IncomingPaymentAllocationItem,
    IncomingPaymentAllocateInput as IncomingPaymentAllocateInput,
    IncomingPaymentUpdateInput as IncomingPaymentUpdateInput,
    IncomingPaymentRefundClaimInput as IncomingPaymentRefundClaimInput,
    IncomingPaymentRevokeInput as IncomingPaymentRevokeInput,
    FinanceSettlementApplyInput as FinanceSettlementApplyInput,
    FinanceSettlementReviewInput as FinanceSettlementReviewInput,
    FinanceSettlementPaymentInput as FinanceSettlementPaymentInput,
    FinanceSettlementReapplyInput as FinanceSettlementReapplyInput,
    ArchiveSettlementPaymentReviewInput as ArchiveSettlementPaymentReviewInput,
    ArchiveSettlementRollbackInput as ArchiveSettlementRollbackInput,
    ArchiveSettlementRejectedActionInput as ArchiveSettlementRejectedActionInput,
    ReconciliationInput as ReconciliationInput,
)
from app.api_schemas.investigation import (
    NotaryReviewInput as NotaryReviewInput,
    ClueReviewInput as ClueReviewInput,
    ClueCollectionInput as ClueCollectionInput,
    ClueBatchCollectionInput as ClueBatchCollectionInput,
    InvestigationPartyInput as InvestigationPartyInput,
    NotaryCertificateInput as NotaryCertificateInput,
    InvestigationTaskInput as InvestigationTaskInput,
    BatchClueCaseInput as BatchClueCaseInput,
    ClueCaseContractResolveInput as ClueCaseContractResolveInput,
    ClueSourceContractBindingInput as ClueSourceContractBindingInput,
    InvestigationAssignmentInput as InvestigationAssignmentInput,
    InvestigationBatchDeleteInput as InvestigationBatchDeleteInput,
    InvestigationFeeInput as InvestigationFeeInput,
    ClueBatchSubmitInput as ClueBatchSubmitInput,
    ClueTurnOnAuditInput as ClueTurnOnAuditInput,
)
from app.api_schemas.cases import (
    CaseAssignmentInput as CaseAssignmentInput,
    CaseHearingLawyerInput as CaseHearingLawyerInput,
    CaseBatchDeleteInput as CaseBatchDeleteInput,
    CaseBatchUpdateInput as CaseBatchUpdateInput,
    CaseMergeInput as CaseMergeInput,
    CaseNotaryInfoInput as CaseNotaryInfoInput,
    CaseSettlementAmountInput as CaseSettlementAmountInput,
    CaseReminderInput as CaseReminderInput,
    CaseEventInput as CaseEventInput,
    CaseEventUpdateInput as CaseEventUpdateInput,
    CaseEventBatchDeleteInput as CaseEventBatchDeleteInput,
    CaseLogInput as CaseLogInput,
    CaseProgressInput as CaseProgressInput,
    CaseCourtInfoInput as CaseCourtInfoInput,
    CaseExecutionStatusInput as CaseExecutionStatusInput,
    CasePhaseChangeInput as CasePhaseChangeInput,
    CaseCreateInput as CaseCreateInput,
    CaseLitigantAgentInput as CaseLitigantAgentInput,
    CasePartyIdentityInput as CasePartyIdentityInput,
    CaseLitigantsInput as CaseLitigantsInput,
    CaseCreationCompleteInput as CaseCreationCompleteInput,
    CaseCounselBasicInput as CaseCounselBasicInput,
    CaseNormalBasicInput as CaseNormalBasicInput,
    CaseArbitrationBasicInput as CaseArbitrationBasicInput,
    CriminalPublicSecurityMaintenanceInput as CriminalPublicSecurityMaintenanceInput,
    CriminalProcuratorateMaintenanceInput as CriminalProcuratorateMaintenanceInput,
    CriminalCourtMaintenanceInput as CriminalCourtMaintenanceInput,
    CounselCaseSearchInput as CounselCaseSearchInput,
    CaseJudicialInput as CaseJudicialInput,
    HearingInput as HearingInput,
    ArchiveCheckInput as ArchiveCheckInput,
    ArchiveReviewInput as ArchiveReviewInput,
    CaseCreationReviewInput as CaseCreationReviewInput,
    CaseUnarchiveRequestInput as CaseUnarchiveRequestInput,
    CaseUnarchiveReviewInput as CaseUnarchiveReviewInput,
)
from app.api_schemas.case_documents import (
    AttachmentBatchInput as AttachmentBatchInput,
    CaseAttachmentRenameInput as CaseAttachmentRenameInput,
    CaseAttachmentMoveInput as CaseAttachmentMoveInput,
    CaseAiDraftCreateInput as CaseAiDraftCreateInput,
    CaseAiDraftUpdateInput as CaseAiDraftUpdateInput,
    CaseAiDraftPromoteInput as CaseAiDraftPromoteInput,
    WordEditorTextBlockInput as WordEditorTextBlockInput,
    CaseWordEditorSaveInput as CaseWordEditorSaveInput,
    CaseWordEditorLockInput as CaseWordEditorLockInput,
    CaseDocumentFolderInput as CaseDocumentFolderInput,
    CaseDocumentFolderRenameInput as CaseDocumentFolderRenameInput,
    TemplateInput as TemplateInput,
    TemplateUpdate as TemplateUpdate,
)
from app.api_schemas.contracts import (
    ContractAttachmentBatchDeleteInput as ContractAttachmentBatchDeleteInput,
    ContractWholeDeleteInput as ContractWholeDeleteInput,
    ContractSubmitInput as ContractSubmitInput,
    ContractApproverSettingsInput as ContractApproverSettingsInput,
    ContractDraftInput as ContractDraftInput,
    ContractApprovalInput as ContractApprovalInput,
    ContractSealApplicationInput as ContractSealApplicationInput,
    ContractInvestigationInput as ContractInvestigationInput,
    ContractChangeInput as ContractChangeInput,
    ContractChangeReviewInput as ContractChangeReviewInput,
    ContractEventInput as ContractEventInput,
    ContractObjectInput as ContractObjectInput,
    ContractArchiveClosureInput as ContractArchiveClosureInput,
    ContractPaymentLineInput as ContractPaymentLineInput,
    ContractPaymentApplicationInput as ContractPaymentApplicationInput,
    ContractPaymentReviewInput as ContractPaymentReviewInput,
    ContractPaymentPayInput as ContractPaymentPayInput,
    ContractPaymentWriteoffInput as ContractPaymentWriteoffInput,
)
from app.api_schemas.ipr import (
    IprCaseCreateInput as IprCaseCreateInput,
    IprCaseUpdateInput as IprCaseUpdateInput,
    IprLitigationCourtInfoInput as IprLitigationCourtInfoInput,
    IprLitigationCourtInput as IprLitigationCourtInput,
    IprLitigationPartyInput as IprLitigationPartyInput,
    IprCaseFeeActionInput as IprCaseFeeActionInput,
    IprCaseFeeArrivalInput as IprCaseFeeArrivalInput,
    IprCaseFeeCreateInput as IprCaseFeeCreateInput,
    IprCaseFeeInvoiceInput as IprCaseFeeInvoiceInput,
    IprCaseFeePaymentApplicationInput as IprCaseFeePaymentApplicationInput,
    IprCaseCrossModuleLinkInput as IprCaseCrossModuleLinkInput,
    IprCaseMaintenanceInput as IprCaseMaintenanceInput,
    IprCaseBatchMaintenanceInput as IprCaseBatchMaintenanceInput,
    IprCaseBatchCreateRow as IprCaseBatchCreateRow,
    IprCaseBatchCreateInput as IprCaseBatchCreateInput,
    IprCaseRebootInput as IprCaseRebootInput,
    IprCaseAnnualFeeMonitoringInput as IprCaseAnnualFeeMonitoringInput,
    IprCaseLogInput as IprCaseLogInput,
    IprCaseReviewInput as IprCaseReviewInput,
    IprCaseLifecycleInput as IprCaseLifecycleInput,
    IprCaseLawFirmReplaceInput as IprCaseLawFirmReplaceInput,
    IprCaseCustomerReplaceInput as IprCaseCustomerReplaceInput,
    IprCaseCustomerContactReplaceInput as IprCaseCustomerContactReplaceInput,
    IprCaseAssistedFeeCreateInput as IprCaseAssistedFeeCreateInput,
    IprCaseAssistedFeeUpdateInput as IprCaseAssistedFeeUpdateInput,
    IprCaseAssistedFeeConfirmInput as IprCaseAssistedFeeConfirmInput,
    IprCaseAnnualFeeCreateInput as IprCaseAnnualFeeCreateInput,
    IprCaseAnnualFeeUpdateInput as IprCaseAnnualFeeUpdateInput,
    IprCaseReminderInput as IprCaseReminderInput,
    IprCaseReminderUpdate as IprCaseReminderUpdate,
    IprCaseReminderSuppressionInput as IprCaseReminderSuppressionInput,
    IprCaseReminderTypeQueryInput as IprCaseReminderTypeQueryInput,
    IprCaseReminderTypeInput as IprCaseReminderTypeInput,
    IprCaseReminderTypeUpdateInput as IprCaseReminderTypeUpdateInput,
    IprCaseWarningRuleInput as IprCaseWarningRuleInput,
    IprCaseWarningRuleUpdateInput as IprCaseWarningRuleUpdateInput,
    IprCaseWarningProcessInput as IprCaseWarningProcessInput,
    IprCaseFileTransmitInput as IprCaseFileTransmitInput,
    IprCaseFileBatchTransmitInput as IprCaseFileBatchTransmitInput,
    IprOfficialFileActionInput as IprOfficialFileActionInput,
    IprOfficialFileBatchActionInput as IprOfficialFileBatchActionInput,
    IprOfficialCandidateMatchInput as IprOfficialCandidateMatchInput,
    IprOfficialCandidateCorrectInput as IprOfficialCandidateCorrectInput,
    IprOfficialCandidateConfirmInput as IprOfficialCandidateConfirmInput,
    IprCaseFileCustomCandidateMatchInput as IprCaseFileCustomCandidateMatchInput,
    IprCaseFileCustomCandidateCorrectInput as IprCaseFileCustomCandidateCorrectInput,
    IprCaseFileCustomCandidateConfirmInput as IprCaseFileCustomCandidateConfirmInput,
    IprOfficialDualStatusInput as IprOfficialDualStatusInput,
)
from app.api_schemas.tasks import (
    TaskInput as TaskInput,
    VipTaskInput as VipTaskInput,
    VipTaskUpdateInput as VipTaskUpdateInput,
    VipTaskNodeInput as VipTaskNodeInput,
    VipTaskNodeUpdateInput as VipTaskNodeUpdateInput,
    VipTaskMessageInput as VipTaskMessageInput,
    VipTaskMessageReadInput as VipTaskMessageReadInput,
    TaskHandoffInput as TaskHandoffInput,
    TaskActionInput as TaskActionInput,
    TaskExceptionRequestInput as TaskExceptionRequestInput,
    TaskExceptionReviewInput as TaskExceptionReviewInput,
    TaskBatchUpdateInput as TaskBatchUpdateInput,
    TaskBatchLifecycleInput as TaskBatchLifecycleInput,
    TaskBatchReadInput as TaskBatchReadInput,
    CaseTaskFinishedInput as CaseTaskFinishedInput,
)
from app.api_schemas.identity import (
    SystemUserInput as SystemUserInput,
    SystemUserUpdate as SystemUserUpdate,
    UserPermissionOverrideUpdate as UserPermissionOverrideUpdate,
    SystemUserPasswordResetInput as SystemUserPasswordResetInput,
    CurrentUserUpdate as CurrentUserUpdate,
    DingTalkLoginInput as DingTalkLoginInput,
    DingTalkBindInput as DingTalkBindInput,
    DingTalkBindingInput as DingTalkBindingInput,
    RolePermissionUpdate as RolePermissionUpdate,
    SecurityPolicyUpdate as SecurityPolicyUpdate,
)
from app.api_schemas.system import (
    CacheBatchClearInput as CacheBatchClearInput,
    SystemParameterInput as SystemParameterInput,
    SystemParameterUpdate as SystemParameterUpdate,
    SystemParameterRelationReplaceInput as SystemParameterRelationReplaceInput,
    SystemConfigUpdate as SystemConfigUpdate,
    SystemMenuUpdate as SystemMenuUpdate,
    SystemMenuVisibilityBatchInput as SystemMenuVisibilityBatchInput,
    SystemMenuInput as SystemMenuInput,
    ReportInput as ReportInput,
)
from app.api_schemas.communications import (
    UserMessageInput as UserMessageInput,
    CommunicationLogInput as CommunicationLogInput,
    CommunicationLogUpdate as CommunicationLogUpdate,
)
from app.api_schemas.customers import (
    CustomerShareInput as CustomerShareInput,
    CustomerActionInput as CustomerActionInput,
    CustomerContactInput as CustomerContactInput,
    CustomerManagersInput as CustomerManagersInput,
    CustomerPatchInput as CustomerPatchInput,
    CustomerEventInput as CustomerEventInput,
    CustomerContactStatusInput as CustomerContactStatusInput,
    CustomerNoteInput as CustomerNoteInput,
    CustomerLevelChangeInput as CustomerLevelChangeInput,
    CustomerLevelReviewInput as CustomerLevelReviewInput,
    CustomerKeyChangeInput as CustomerKeyChangeInput,
    CustomerKeyChangeReviewInput as CustomerKeyChangeReviewInput,
    CustomerPortalActionInput as CustomerPortalActionInput,
    CustomerPortalLoginInput as CustomerPortalLoginInput,
    CustomerPortalDemandInput as CustomerPortalDemandInput,
    CustomerPortalActivationInput as CustomerPortalActivationInput,
    CustomerCreateInput as CustomerCreateInput,
)
from app.api_schemas.seals import (
    SealApplicationInput as SealApplicationInput,
    SealPackageDownloadInput as SealPackageDownloadInput,
    SealBatchApplicationInput as SealBatchApplicationInput,
    SealApprovalInput as SealApprovalInput,
    SealStampInput as SealStampInput,
    SealBatchStampInput as SealBatchStampInput,
    SealAssetInput as SealAssetInput,
    SealAssetUpdate as SealAssetUpdate,
)

from datetime import date as date, datetime as datetime
from pydantic import BaseModel as BaseModel, Field as Field, field_validator as field_validator, model_validator as model_validator
from typing import Literal as Literal
