import { paymentPrintStatusField } from "../constants";
import type { OriginalFieldSpec, OriginalRouteConfig } from "../types";
export function createRouteConfigs(context: {
    readonly f: (label: string, options?: Partial<Omit<OriginalFieldSpec, "label">> | undefined) => OriginalFieldSpec;
    readonly initialView: string;
    readonly bankFields: OriginalFieldSpec[];
    readonly receiptFields: OriginalFieldSpec[];
    readonly receiptQueryFields: OriginalFieldSpec[];
    readonly internalSettleFields: OriginalFieldSpec[];
    readonly internalApprovalFields: OriginalFieldSpec[];
    readonly internalListFields: OriginalFieldSpec[];
    readonly internalPaymentFields: OriginalFieldSpec[];
    readonly paymentPackageFields: OriginalFieldSpec[];
    readonly internalDetailFields: OriginalFieldSpec[];
    readonly invoiceMineFields: OriginalFieldSpec[];
    readonly invoiceFields: OriginalFieldSpec[];
    readonly unissuedFields: OriginalFieldSpec[];
    readonly settlementPendingFields: OriginalFieldSpec[];
    readonly settlementFields: OriginalFieldSpec[];
    readonly archiveFields: OriginalFieldSpec[];
    readonly paymentStatuses: string[];
}): Record<string, OriginalRouteConfig> {
    return {
        "finance-payment-print": {
            fields: [
                context.f("申请日期", { control: "date" }),
                context.f("付款状态", paymentPrintStatusField(context.initialView)),
                context.f("申请人"),
                context.f("付款日期", { control: "date" }),
                context.f("合同号"),
                context.f("案件编号"),
                context.f("收款单位"),
                context.f("请款单号"),
                context.f("费用类型"),
                context.f("客户名称"),
            ],
            source: "fees",
            selectable: true,
            clear: true,
            export: true,
            headers: [
                "操作",
                "请款单号",
                "状态",
                "申请日期",
                "申请金额",
                "截止日期",
                "案件编号",
                "案件阶段",
                "合同编号",
                "付款日期",
                "申请人",
                "客户管理人",
                "交款人",
            ],
        },
        "finance-payment-package-manage": {
            fields: [
                context.f("付款包号码"),
                context.f("付款状态", { options: ["待核销", "已付款"] }),
                context.f("收款单位"),
                context.f("付款日期", { control: "date" }),
            ],
            source: "paymentPackages",
            clear: true,
            headers: ["操作", "付款包号码", "付款状态", "收款单位", "付款总金额", "付款日期", "制单人", "备注"],
            note: "付款包号不可修改；仅待核销付款包可调整费用构成和备注。",
        },
        "finance-receipts-icbc": {
            fields: context.bankFields,
            source: "incoming",
            selectable: true,
            upload: true,
            headers: [
                "管家卡卡号/收款账号",
                "管家卡卡名称/收款名称",
                "对方账号/回款账号",
                "对方户名/回款单位",
                "金额/回款金额",
                "收付款标志/回款方式",
                "收付款日期/回款日期",
                "渠道",
                "流水号",
                "备注",
                "摘要",
                "状态",
            ],
        },
        "finance-receipts-citic": {
            fields: context.bankFields,
            source: "incoming",
            selectable: true,
            upload: true,
            headers: [
                "收款账号",
                "收款银行",
                "对方账号/回款账号",
                "对方户名/回款单位",
                "金额/回款金额",
                "收付款标志/回款方式",
                "收付款日期/回款日期",
                "对方账号开户网点名称",
                "柜员交易号",
                "备注",
                "状态",
            ],
        },
        "finance-receipts-boc": {
            fields: context.bankFields,
            source: "incoming",
            selectable: true,
            upload: true,
            headers: [
                "交易类型/回款方式",
                "交易日期/回款日期",
                "付款人账号/回款账号",
                "付款人名称/回款单位",
                "交易金额/回款金额",
                "交易流水号/银行单号",
                "摘要",
                "用途",
                "交易附言",
                "备注",
                "状态",
            ],
        },
        ...Object.fromEntries([
            "finance-receipts-manage",
            "finance-receipts-claim",
            "finance-receipts-pending",
            "finance-receipts-allocated",
        ].map((route) => [
            route,
            {
                fields: context.receiptFields,
                source: "incoming",
                selectable: true,
                headers: [
                    "操作",
                    "客户名称",
                    "客户管理人",
                    "回款单位",
                    "回款日期",
                    "回款金额",
                    "已分金额",
                    "未分金额",
                    "已分官费",
                    "已分代理费",
                    "已分其他费用",
                    "回款方式",
                    "合同编号",
                    "备注",
                ],
            },
        ])),
        "finance-receipts-query": {
            fields: context.receiptQueryFields,
            source: "incoming",
            selectable: true,
            clear: true,
            export: true,
            headers: [
                "案号",
                "客户",
                "开庭律师",
                "律师助理",
                "案源人",
                "客户管理人",
                "调查人",
                "费用类型",
                "金额",
                "到账时间",
                "到账单位",
                "到账金额",
                "合同号",
            ],
        },
        "finance-internal-settle": {
            fields: context.internalSettleFields,
            source: "settlements",
            selectable: true,
            clear: true,
            export: true,
            headers: [
                "案号",
                "原告",
                "被告",
                "金额",
                "回款单位",
                "到账金额",
                "到账时间",
                "结算状态",
                "案件阶段",
                "案源人",
                "开庭律师",
                "律师助理",
                "调查员",
                "品管",
            ],
        },
        ...Object.fromEntries([
            "finance-internal-archive",
            "finance-internal-audit",
            "finance-internal-fee-audit",
        ].map((route) => [
            route,
            {
                fields: context.internalApprovalFields,
                source: "fees",
                selectable: true,
                headers: [
                    "操作",
                    "请款单号",
                    "状态",
                    "申请日期",
                    "申请金额",
                    "案件编号",
                    "案件阶段",
                    "案件名称",
                    "申请人",
                    "客户名称",
                ],
            },
        ])),
        "finance-internal-refund-audit": {
            fields: context.internalApprovalFields,
            source: "refundReviewFees",
            selectable: true,
            headers: [
                "操作",
                "请款单号",
                "状态",
                "申请日期",
                "申请金额",
                "案件编号",
                "案件阶段",
                "案件名称",
                "申请人",
                "客户名称",
            ],
        },
        ...Object.fromEntries(["finance-internal-refused", "finance-internal-void"].map((route) => [
            route,
            {
                fields: context.internalListFields,
                source: "fees",
                headers: [
                    "操作",
                    "请款单号",
                    "状态",
                    "申请日期",
                    "审核日期",
                    "申请金额",
                    "案件编号",
                    "案件阶段",
                    "案件名称",
                    "付款日期",
                    "申请人",
                    "",
                ],
            },
        ])),
        "finance-internal-payment": {
            fields: context.internalPaymentFields,
            source: "fees",
            selectable: true,
            headers: [
                "操作",
                "状态",
                "申请人",
                "申请日期",
                "审核日期",
                "收款人",
                "提成类型",
                "基数",
                "参考提成",
                "实际提成",
                "案件编号",
                "案件阶段",
                "案件名称",
                "付款日期",
            ],
        },
        ...Object.fromEntries(["finance-internal-writeoff", "finance-internal-done"].map((route) => [
            route,
            {
                fields: context.paymentPackageFields,
                source: "paymentPackages",
                clear: ["finance-internal-writeoff", "finance-internal-done"].includes(route),
                headers: [
                    "操作",
                    "付款包号码",
                    "收款人",
                    "付款总金额",
                    "付款状态",
                    "付款日期",
                    "付款单据号",
                    "备注",
                ],
            },
        ])),
        "finance-internal-query": {
            fields: context.internalListFields,
            source: "fees",
            headers: [
                "操作",
                "请款单号",
                "状态",
                "申请日期",
                "审核日期",
                "申请金额",
                "案件编号",
                "案件阶段",
                "案件名称",
                "付款日期",
                "申请人",
                "",
            ],
        },
        ...Object.fromEntries(["finance-internal-detail", "finance-internal-company"].map((route) => [
            route,
            {
                fields: context.internalDetailFields,
                source: "fees",
                selectable: true,
                clear: true,
                export: true,
                headers: [
                    "案号",
                    "案件阶段",
                    "原告",
                    "被告",
                    "经办律师",
                    "律师助理",
                    "案源人",
                    "调查人",
                    "归档时间",
                    "申请时间",
                    "内部费用类型",
                    "金额",
                    "收款人",
                    "支付状态",
                    "",
                ],
            },
        ])),
        "finance-invoice-mine": {
            fields: context.invoiceMineFields,
            source: "invoices",
            selectable: true,
            export: true,
            headers: [
                "操作",
                "请票单号",
                "客户名称",
                "开票金额",
                "高开金额",
                "发票编号",
                "领票人",
                "开票日期",
                "票据状态",
                "备注",
                "",
            ],
        },
        "finance-invoice-pending": {
            fields: context.invoiceFields,
            source: "invoices",
            selectable: true,
            export: true,
            headers: [
                "操作",
                "请票单号",
                "申请人",
                "客户名称",
                "开票金额",
                "高开金额",
                "开票抬头",
                "备注",
                "",
            ],
        },
        "finance-invoice-company": {
            fields: context.invoiceFields,
            source: "invoices",
            selectable: true,
            export: true,
            headers: [
                "操作",
                "请票单号",
                "客户名称",
                "开票金额",
                "高开金额",
                "开票抬头",
                "发票号码",
                "申请人",
                "领票人",
                "开票日期",
                "状态",
                "",
            ],
        },
        ...Object.fromEntries(["finance-invoice-unissued", "finance-invoice-company-unissued"].map((route) => [
            route,
            {
                fields: context.unissuedFields,
                source: "unissuedFees",
                selectable: true,
                clear: true,
                export: true,
                headers: [
                    "案号",
                    "客户",
                    "案件阶段",
                    "助理",
                    "开庭律师",
                    "法院案号",
                    "费用类型",
                    "金额",
                    "开票日期",
                    "开票金额",
                    "发票查看",
                    "到账时间",
                    "到账金额",
                    "到账单位",
                    "付款时间",
                    "付款金额",
                    "法院名称",
                    "付款状态",
                    "",
                ],
            },
        ])),
        "finance-settlement-pending": {
            fields: context.settlementPendingFields,
            source: "generalSettlements",
            selectable: true,
            headers: [
                "操作",
                "客户名称",
                "客户管理人",
                "回款单位",
                "回款日期",
                "回款金额",
                "已分金额",
                "未分金额",
                "已分官费",
                "已分代理费",
                "已分其他费用",
                "代理费结算金额",
                "扣归档费",
                "实际结算金额",
                "",
            ],
        },
        "finance-settlement-audit": {
            fields: context.settlementFields,
            source: "generalSettlements",
            selectable: true,
            headers: [
                "操作",
                "客户名称",
                "客户管理人",
                "回款单位",
                "回款日期",
                "回款金额",
                "已分金额",
                "未分金额",
                "已分官费",
                "已分代理费",
                "已分其他费用",
                "代理费结算金额",
                "扣归档费",
                "实际结算金额",
                "",
            ],
        },
        "finance-settlement-payment": {
            fields: context.settlementFields,
            source: "generalSettlements",
            selectable: true,
            headers: [
                "操作",
                "客户名称",
                "客户管理人",
                "回款单位",
                "回款日期",
                "回款金额",
                "已分金额",
                "未分金额",
                "已分官费",
                "已分代理费",
                "已分其他费用",
                "代理费结算金额",
                "扣归档费",
                "实际结算金额",
                "",
            ],
        },
        "finance-settlement-paid": {
            fields: context.settlementFields,
            source: "generalSettlements",
            selectable: true,
            clear: true,
            export: true,
            headers: [
                "操作",
                "客户名称",
                "客户管理人",
                "回款单位",
                "回款日期",
                "回款金额",
                "已分金额",
                "未分金额",
                "已分官费",
                "已分代理费",
                "已分其他费用",
                "代理费结算金额",
                "扣归档费",
                "实际结算金额",
                "",
            ],
        },
        "finance-settlement-refused": {
            fields: context.settlementFields,
            source: "generalSettlements",
            selectable: true,
            clear: true,
            export: true,
            headers: [
                "操作",
                "客户名称",
                "客户管理人",
                "回款单位",
                "回款日期",
                "回款金额",
                "已分金额",
                "未分金额",
                "已分官费",
                "已分代理费",
                "已分其他费用",
                "代理费结算金额",
                "扣归档费",
                "实际结算金额",
                "",
            ],
        },
        ...Object.fromEntries([
            "finance-archive-fee-pending",
            "finance-archive-fee-payment",
            "finance-archive-fee-paid",
            "finance-archive-fee-refused",
        ].map((route) => [
            route,
            {
                fields: context.archiveFields,
                source: [
                    "finance-archive-fee-pending",
                    "finance-archive-fee-payment",
                    "finance-archive-fee-paid",
                    "finance-archive-fee-refused",
                ].includes(route)
                    ? "archiveSettlements"
                    : "fees",
                selectable: true,
                clear: [
                    "finance-archive-fee-pending",
                    "finance-archive-fee-payment",
                    "finance-archive-fee-paid",
                    "finance-archive-fee-refused",
                ].includes(route),
                export: [
                    "finance-archive-fee-pending",
                    "finance-archive-fee-payment",
                    "finance-archive-fee-paid",
                    "finance-archive-fee-refused",
                ].includes(route),
                headers: [
                    "操作",
                    "案号",
                    "客户",
                    "案件阶段",
                    "律师助理",
                    "开庭律师",
                    "客户管理人",
                    "费用类型",
                    "回款方式",
                    "回款时间",
                    "回款金额",
                    "归档费金额",
                    ...(route === "finance-archive-fee-payment"
                        ? ["支付时间"]
                        : route === "finance-archive-fee-refused"
                            ? ["结算时间", "支付状态"]
                            : ["结算时间"]),
                    "",
                ],
            },
        ])),
        "finance-fee-query": {
            fields: [
                context.f("案件编号"),
                context.f("法院案号"),
                context.f("公证书号"),
                context.f("退费金额", { control: "money" }),
                context.f("客户名称"),
                context.f("收款单位"),
                context.f("付款状态", { options: context.paymentStatuses }),
                context.f("付款时间", { control: "date" }),
                context.f("开庭律师"),
                context.f("律师助理"),
                context.f("案件阶段"),
                context.f("费用类型", {
                    control: "multi",
                    pickerLabel: "从下列案件阶段中选择",
                    options: [
                        "官费",
                        "一审诉讼费",
                        "二审诉讼费",
                        "再审诉讼费",
                        "公证费",
                        "调解金额",
                        "判决金额",
                        "保全费",
                        "执行费",
                        "核定成本",
                        "代理费",
                        "其他费用",
                        "内部费用",
                        "第三方费用",
                    ],
                }),
            ],
            source: "feeQuery",
            selectable: true,
            clear: true,
            export: true,
            headers: [
                "案号",
                "客户",
                "案件阶段",
                "助理",
                "开庭律师",
                "法院案号",
                "费用类型",
                "金额",
                "退费金额",
                "已退金额",
                "到账时间",
                "到账金额",
                "付款时间",
                "付款金额",
                "法院名称",
                "付款状态",
            ],
        },
        "finance-refund": {
            fields: [
                context.f("案件编号"),
                context.f("法院案号"),
                context.f("法院名称"),
                context.f("付款时间", { control: "date" }),
                context.f("客户名称"),
                context.f("收款单位"),
                context.f("退费进度", {
                    options: [
                        "准备材料",
                        "已提交法院",
                        "法院处理中",
                        "待退款到账",
                        "退款已到账",
                        "退费完成",
                    ],
                }),
                context.f("退费金额", { control: "money" }),
                context.f("开庭律师"),
                context.f("律师助理"),
                context.f("案件阶段"),
                context.f("费用类型", {
                    control: "multi",
                    pickerLabel: "选择费用类型",
                    options: [
                        "官费",
                        "一审诉讼费",
                        "二审诉讼费",
                        "再审诉讼费",
                        "公证费",
                        "保全费",
                        "执行费",
                        "代理费",
                        "其他费用",
                    ],
                }),
            ],
            source: "feeQuery",
            selectable: true,
            clear: true,
            export: true,
            headers: [
                "案号",
                "原告",
                "被告",
                "案件阶段",
                "律师助理",
                "开庭律师",
                "费用类型",
                "金额",
                "退费金额",
                "新建时间",
                "法院名称",
                "退费进度",
                "进度时长",
                "操作",
            ],
        },
    };
}
