export const originalFinanceRoutes = [
    "finance-receipts-icbc",
    "finance-receipts-citic",
    "finance-receipts-boc",
    "finance-receipts-cmb",
    "finance-receipts-manage",
    "finance-receipts-claim",
    "finance-receipts-pending",
    "finance-receipts-allocated",
    "finance-receipts-query",
    "finance-payment-mine",
    "finance-payment-audit",
    "finance-payment-waiting",
    "finance-payment-print",
    "finance-payment-package-manage",
    "finance-payment-writeoff",
    "finance-payment-query",
    "finance-internal-mine",
    "finance-internal-settle",
    "finance-internal-archive",
    "finance-internal-audit",
    "finance-internal-fee-audit",
    "finance-internal-refused",
    "finance-internal-void",
    "finance-internal-refund-audit",
    "finance-internal-payment",
    "finance-internal-writeoff",
    "finance-internal-query",
    "finance-internal-done",
    "finance-internal-detail",
    "finance-internal-company",
    "finance-invoice-mine",
    "finance-invoice-pending",
    "finance-invoice-company",
    "finance-invoice-unissued",
    "finance-invoice-company-unissued",
    "finance-settlement-pending",
    "finance-settlement-audit",
    "finance-settlement-payment",
    "finance-settlement-paid",
    "finance-settlement-refused",
    "finance-archive-fee-pending",
    "finance-archive-fee-payment",
    "finance-archive-fee-paid",
    "finance-archive-fee-refused",
    "finance-query",
    "finance-fee-query",
    "finance-refund",
  ];
export const originalFinanceTitles: Record<string, string> = {
    "finance-receipts-icbc": "工行银行到账列表",
    "finance-receipts-citic": "中信银行到账列表",
    "finance-receipts-boc": "中国银行到账列表",
    "finance-receipts-cmb": "招商银行到账列表",
    "finance-receipts-manage": "回款查询",
    "finance-receipts-claim": "回款查询",
    "finance-receipts-pending": "回款查询",
    "finance-receipts-allocated": "回款查询",
    "finance-receipts-query": "到账查询",
    "finance-payment-mine": "我的请款单",
    "finance-payment-audit": "请款单审批",
    "finance-payment-waiting": "请款单列表",
    "finance-payment-print": "请款单列表",
    "finance-payment-package-manage": "付款打包-管理",
    "finance-payment-writeoff": "请款单列表",
    "finance-payment-query": "请款单列表",
    "finance-refund-not-required": "不再办理退费案件",
    "finance-internal-mine": "我的请款单",
    "finance-internal-settle": "内部提成-待结算",
    "finance-internal-archive": "内部提成-待归档",
    "finance-internal-audit": "请款单审批",
    "finance-internal-fee-audit": "请款单审批",
    "finance-internal-refused": "请款单列表",
    "finance-internal-void": "请款单列表",
    "finance-internal-refund-audit": "请款单审批",
    "finance-internal-payment": "待付款列表",
    "finance-internal-writeoff": "付款单-核销",
    "finance-internal-query": "请款单列表",
    "finance-internal-done": "付款单-查询",
    "finance-internal-detail": "内部费用查询",
    "finance-internal-company": "内部费用查询",
    "finance-invoice-mine": "我的开票",
    "finance-invoice-pending": "待处理开票",
    "finance-invoice-company": "公司开票",
    "finance-invoice-unissued": "未开票",
    "finance-invoice-company-unissued": "公司未开票",
    "finance-settlement-pending": "待结算",
    "finance-settlement-audit": "待审核",
    "finance-settlement-payment": "待付款",
    "finance-settlement-paid": "已付款",
    "finance-settlement-refused": "已拒绝",
    "finance-archive-fee-pending": "待归档",
    "finance-archive-fee-payment": "待支付",
    "finance-archive-fee-paid": "已支付",
    "finance-archive-fee-refused": "已拒绝",
    "finance-query": "费用查询",
    "finance-fee-query": "费用查询",
    "finance-refund": "退费查询",
  };
