export type IprRecord = {
  id: number;
  serial_no: string;
  title: string;
  customer: string;
  owner: string;
  owner_display_name?: string;
  status: string;
  description: string;
  data: Record<string, any>;
  updated_at: string;
};
export type IprLawsuitCourt = { id: string; court_level: string; court_name: string; case_no?: string; judge?: string; clerk?: string; courtroom?: string; filing_date?: string; hearing_date?: string; remark?: string };
export type IprLawsuitParty = { id: string; party_type: string; name: string; contact_name?: string; contact_phone?: string; address?: string; remark?: string };
export type IprLawsuitFee = { id: number; fee_type?: string; title?: string; amount?: number; status?: string; fee_date?: string; remark?: string };
export type LegacyIprCaseListItem = {
  legacy_case_id: number;
  case_no: string;
  title: string;
  case_type: string;
  applicant: string;
  deadline?: string | null;
  relationship_state: string;
  current_case_record_id: number | null;
};
export type Customer = { id: number; title: string; serial_no: string };
export type PeopleOption = { username: string; label: string };
export type Attachment = {
  id: number;
  original_name: string;
  size: number;
  uploader: string;
  uploader_display_name?: string;
  category?: string;
  document_date?: string | null;
  requires_transmission?: boolean;
  is_transmitted?: boolean;
  transmitted_by?: string;
  transmitted_by_display_name?: string;
};
export type IprFileType = {
  code: string;
  name: string;
  case_kinds: string[];
  is_official: boolean;
  requires_transmission: boolean;
  allow_repeat: boolean;
};
export type AssistedFee = {
  id: number;
  assisted_type: string;
  status: string;
  request_date: string;
  request_user: string;
  request_user_display_name?: string;
  response_date: string | null;
  response_user: string;
  response_user_display_name?: string;
  remark: string;
  receipt: Attachment | null;
};
export type AnnualFee = {
  id: number;
  fee_year: number;
  fee_name: string;
  amount: number | null;
  currency?: string;
  due_date: string;
  paid_date: string | null;
  status: "待缴" | "已缴" | "未缴" | string;
  reminder_date: string | null;
  reminder_id?: number | null;
  reminder_sent?: boolean;
  notes?: string;
};
export type IprCaseEvent = {
  id: number;
  event_type_id: number;
  event_type: string;
  event_date: string;
  deadline: string;
  content: string;
  creator: string;
  creator_display_name?: string;
};
export type IprCaseTask = {
  id: number;
  serial_no: string;
  title: string;
  customer: string;
  owner: string;
  owner_display_name?: string;
  status: string;
  deadline?: string;
  priority?: string;
  description?: string;
  case_record_id?: number;
  case_module?: string;
  case_no?: string;
};
export type IprReminderTypeQuery = {
  case_kind?: string;
  case_type?: string;
  case_phase?: string;
  statuses?: string[];
  event_type_ids?: number[];
  annual_fee_monitoring?: boolean | null;
  deadline_from?: string;
  deadline_to?: string;
  deadline_within_days?: number | null;
};
export type IprReminderType = {
  id: number;
  name: string;
  query_object: IprReminderTypeQuery;
  is_default: boolean;
  is_active: boolean;
  sort_order: number;
  case_count: number;
  created_by: string;
  updated_by: string;
};
export type IprReminderEventOption = { id: number; name: string };
export type IprWarningRule = {
  id: number;
  name: string;
  case_kind?: "专利" | "商标" | "";
  case_type?: string;
  case_phase?: string;
  time_node: "case_deadline" | "reminder_deadline";
  event_type_id?: number | null;
  days_before: number;
  is_active: boolean;
  created_by?: string;
  updated_by?: string;
};
export type IprWarning = {
  id: number;
  rule_id: number;
  case_id: number;
  case_no: string;
  case_title: string;
  case_kind: string;
  reminder_id?: number | null;
  due_date: string;
  title: string;
  content: string;
  recipient: string;
  status: "未读" | "已读" | "已处理";
  is_read: boolean;
  read_at?: string | null;
  processed_at?: string | null;
  processed_by?: string | null;
  process_comment?: string | null;
  created_at: string;
  notification_id?: number | null;
};
export type ReminderEventType = { id: number; name: string; suppressed: boolean };
export type IprLawFirm = { id: number; law_firm_id: number; code: string; name: string; phone: string; email: string };
export type IprLawFirmCandidate = { id: number; code: string; name: string; phone: string; email: string; selected: boolean };
export type IprCaseCustomer = { id: number | null; customer_id: number; customer_no: string; name: string; status: string; is_primary: boolean };
export type IprCaseCustomerCandidate = { id: number; customer_no: string; name: string; status: string; selected: boolean };
export type CustomerContact = { id: string; name: string; phone?: string; email?: string; position?: string; is_valid?: boolean };
export type IprCaseContact = CustomerContact & { customer_id: number; customer_name: string; contact_id: string; contact_role: "document" | "technology" };
export type IprBusinessLog = { id: number; content: string; created_by: string; created_by_display_name?: string; created_at: string };
export type IprOperationLog = { id: number; action: string; operator: string; operator_display_name?: string; comment: string; from_status?: string; to_status?: string; created_at: string };
export type IprHistoryItem = { id: number; action: string; operator: string; operator_display_name?: string; comment?: string; from_status?: string; to_status?: string; created_at: string };
export type CpcApplication = {
  id: number;
  case_id: number;
  case_no: string;
  original_name: string;
  content_type: string;
  size: number;
  created_at: string;
  created_by: string;
  status: string;
  download_url: string;
  format: string;
};
export type IprBatchCreateError = { row_no: number; message: string; errors: Record<string, string> };
export type IprDetailPageState = { page: number; pageSize: number; total: number; pages: number };
export type IprDetailPagePayload<T> = { items?: T[]; total?: number; page?: number; page_size?: number; pages?: number; capabilities?: Record<string, boolean> };
export type AnnualFeePagePayload = IprDetailPagePayload<AnnualFee> & { capabilities?: { can_manage?: boolean } };
export type IprFinanceFeeType = "官方费用" | "代理费" | "其他费用" | "内部费用" | "结算费用" | "预损费用" | "归档费用";
